//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class IPPerson, NSArray, NSDate, NSString;

@interface IPMessage : NSObject
{
    NSArray *_messageUnits;
    NSString *_identifier;
    NSString *_subject;
    IPPerson *_sender;
    NSArray *_recipients;
    NSDate *_dateSent;
    NSString *_htmlContent;
}

@property(retain) NSString *htmlContent; // @synthesize htmlContent=_htmlContent;
@property(retain, nonatomic) NSArray *messageUnits; // @synthesize messageUnits=_messageUnits;
@property(retain) NSDate *dateSent; // @synthesize dateSent=_dateSent;
@property(retain) NSArray *recipients; // @synthesize recipients=_recipients;
@property(retain) IPPerson *sender; // @synthesize sender=_sender;
@property(retain) NSString *subject; // @synthesize subject=_subject;
@property(retain) NSString *identifier; // @synthesize identifier=_identifier;
- (void).cxx_destruct;
- (id)initWithHTMLContent:(id)arg1 emailHeadersDictionary:(id)arg2 dateSent:(id)arg3;
- (id)firstHeaderValueForKey:(id)arg1 inHeaders:(id)arg2;
- (id)initWithIdentifier:(id)arg1 subject:(id)arg2 sender:(id)arg3 recipients:(id)arg4 dateSent:(id)arg5;
- (id)init;

@end

