//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <HealthKit/NSObject-Protocol.h>

@class NSArray, NSDate, NSDictionary, NSError;

@protocol _HKActiveWorkoutClient <NSObject>
- (void)serverFailedWithError:(NSError *)arg1;
- (void)serverStoppedWithDate:(NSDate *)arg1;
- (void)serverPausedWithDate:(NSDate *)arg1 completion:(void (^)(_Bool, NSError *))arg2;
- (void)updateTotalsWithQuantities:(NSDictionary *)arg1 resumeData:(NSDictionary *)arg2 UUIDs:(NSArray *)arg3;
@end

