//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import <HealthKit/NSSecureCoding-Protocol.h>

@class HKSampleType, _HKFilter;

__attribute__((visibility("hidden")))
@interface _HKQueryServerDataObject : NSObject <NSSecureCoding>
{
    _Bool _shouldStayAliveAfterInitialResults;
    HKSampleType *_sampleType;
    _HKFilter *_filter;
}

+ (_Bool)supportsSecureCoding;
@property(nonatomic) _Bool shouldStayAliveAfterInitialResults; // @synthesize shouldStayAliveAfterInitialResults=_shouldStayAliveAfterInitialResults;
@property(retain, nonatomic) _HKFilter *filter; // @synthesize filter=_filter;
@property(retain, nonatomic) HKSampleType *sampleType; // @synthesize sampleType=_sampleType;
- (void).cxx_destruct;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;

@end

