//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <HealthKit/NSObject-Protocol.h>

@class HKAuthorizationRequestRecord, HKHealthService, NSArray, NSDate, NSDictionary, NSError, NSString, NSUUID;

@protocol HKClientInterface <NSObject>
- (void)deliverWorkoutSessionError:(NSError *)arg1 forSessionUUID:(NSUUID *)arg2;
- (void)deliverWorkoutSessionChangedToState:(long long)arg1 fromState:(long long)arg2 date:(NSDate *)arg3 forSessionUUID:(NSUUID *)arg4;
- (void)unitPreferencesDidUpdate;
- (void)deliverSessionCharacteristics:(NSArray *)arg1 forService:(NSString *)arg2 toClient:(unsigned long long)arg3 withError:(NSError *)arg4;
- (void)deliverSessionTransitoryData:(NSDictionary *)arg1 toClient:(unsigned long long)arg2 withError:(NSError *)arg3;
- (void)deliverSessionHealthServiceStatus:(long long)arg1 toClient:(unsigned long long)arg2 finished:(_Bool)arg3 withError:(NSError *)arg4;
- (void)deliverDiscoveryHealthService:(HKHealthService *)arg1 toClient:(unsigned long long)arg2 finished:(_Bool)arg3 withError:(NSError *)arg4;
- (void)deliverBluetoothStatus:(long long)arg1 withError:(NSError *)arg2;
- (void)presentAuthorizationWithRequestRecord:(HKAuthorizationRequestRecord *)arg1 completion:(void (^)(_Bool, NSError *))arg2;
@end

