//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <FrontBoardServices/FBSSystemServiceFacilityClient.h>

@interface FBSApplicationTerminationAssertionClient : FBSSystemServiceFacilityClient
{
}

+ (id)sharedInstance;
- (void)sendRelinquishTerminationAssertion:(id)arg1;
- (void)sendAcquireTerminationAssertion:(id)arg1 handler:(CDUnknownBlockType)arg2;
- (id)_messageWithAssertion:(id)arg1;

@end

