//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

#import <FrontBoardServices/BSDescriptionProviding-Protocol.h>
#import <FrontBoardServices/BSXPCCoding-Protocol.h>
#import <FrontBoardServices/NSCopying-Protocol.h>
#import <FrontBoardServices/NSSecureCoding-Protocol.h>

@class CADisplay, NSString;

@interface FBSDisplay : NSObject <BSDescriptionProviding, BSXPCCoding, NSCopying, NSSecureCoding>
{
    unsigned int _seed;
    long long _tags;
    int _pid;
    unsigned long long _type;
    unsigned int _displayID;
    NSString *_uniqueID;
    CADisplay *_caDisplay;
    struct CGRect _referenceBounds;
    double _scale;
    double _orientation;
    _Bool _external;
}

+ (id)_CADisplayForId:(unsigned int)arg1;
+ (_Bool)supportsSecureCoding;
+ (id)_nameForDisplayType:(unsigned long long)arg1;
@property(readonly, copy, nonatomic) NSString *uniqueID; // @synthesize uniqueID=_uniqueID;
@property(readonly, nonatomic) struct CGRect referenceBounds; // @synthesize referenceBounds=_referenceBounds;
@property(readonly, nonatomic) double orientation; // @synthesize orientation=_orientation;
@property(readonly, nonatomic) double scale; // @synthesize scale=_scale;
@property(readonly, nonatomic) int pid; // @synthesize pid=_pid;
@property(readonly, nonatomic, getter=isExternal) _Bool external; // @synthesize external=_external;
@property(readonly, nonatomic) long long tags; // @synthesize tags=_tags;
@property(nonatomic) unsigned int seed; // @synthesize seed=_seed;
@property(readonly, nonatomic) unsigned long long type; // @synthesize type=_type;
@property(readonly, nonatomic) unsigned int displayID; // @synthesize displayID=_displayID;
- (_Bool)isWatchOnlyDisplay;
- (_Bool)isConnected;
- (unsigned long long)_typeFromTags:(unsigned long long)arg1;
- (id)descriptionBuilderWithMultilinePrefix:(id)arg1;
- (id)descriptionWithMultilinePrefix:(id)arg1;
- (id)succinctDescriptionBuilder;
- (id)succinctDescription;
- (void)encodeWithXPCDictionary:(id)arg1;
- (id)initWithXPCDictionary:(id)arg1;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)copyWithZone:(struct _NSZone *)arg1;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
- (_Bool)isEqual:(id)arg1;
- (id)_nameForDisplayType;
- (_Bool)isHiddenDisplay;
- (_Bool)isMusicOnlyDisplay;
- (_Bool)isMainDisplay;
- (_Bool)isiPodOnlyDisplay;
- (_Bool)isCarDisplay;
- (_Bool)isRestrictedAirPlayDisplay;
- (_Bool)isAirPlayDisplay;
@property(readonly, retain, nonatomic) CADisplay *caDisplay; // @synthesize caDisplay=_caDisplay;
- (void)dealloc;
- (id)initWithCADisplay:(id)arg1 isMainDisplay:(_Bool)arg2;
- (id)initWithCADisplay:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly) Class superclass;

@end

