//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class NSMutableDictionary;

@interface TUMetadataItem : NSObject
{
    NSMutableDictionary *_callMetadata;
}

@property(retain, nonatomic) NSMutableDictionary *callMetadata; // @synthesize callMetadata=_callMetadata;
- (void).cxx_destruct;
- (_Bool)isEmpty;
- (id)description;
- (id)metadataForProvider:(Class)arg1;
- (void)setMetadata:(id)arg1 forProvider:(Class)arg2;
- (id)init;

@end

