//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

#import <EventKit/EKIdentityProtocol-Protocol.h>

@class NSString, NSURL;

@interface EKCalendarEventInvitationNotificationAttendee : NSObject <EKIdentityProtocol>
{
    _Bool _statusChanged;
    _Bool _commentChanged;
    NSString *_name;
    NSString *_firstName;
    NSString *_lastName;
    NSString *_emailAddress;
    NSURL *_url;
    long long _participantStatus;
    NSString *_comment;
}

@property(readonly, nonatomic) NSString *comment; // @synthesize comment=_comment;
@property(readonly, nonatomic) long long participantStatus; // @synthesize participantStatus=_participantStatus;
@property(readonly, nonatomic) _Bool commentChanged; // @synthesize commentChanged=_commentChanged;
@property(readonly, nonatomic) _Bool statusChanged; // @synthesize statusChanged=_statusChanged;
@property(readonly, nonatomic) NSURL *url; // @synthesize url=_url;
@property(readonly, nonatomic) NSString *emailAddress; // @synthesize emailAddress=_emailAddress;
@property(readonly, nonatomic) NSString *lastName; // @synthesize lastName=_lastName;
@property(readonly, nonatomic) NSString *firstName; // @synthesize firstName=_firstName;
@property(readonly, nonatomic) NSString *name; // @synthesize name=_name;
- (void)dealloc;
- (id)initWithAttendee:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

