//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UITableViewController.h>

#import <MapKit/MKTransitDeparturesCellDelegate-Protocol.h>
#import <MapKit/_MKPlaceTransitIncidentCellDelegate-Protocol.h>
#import <MapKit/_MKTransitConnectionCellDelegate-Protocol.h>

@class MKMapItem, NSDate, NSMapTable, NSMutableArray, NSMutableDictionary, NSMutableSet, NSString, NSTimer, _MKPlaceTransitIncidentsController;
@protocol GEOTransitSystem, MKTransitDepaturesViewControllerDelegate;

__attribute__((visibility("hidden")))
@interface MKTransitDeparturesViewController : UITableViewController <_MKTransitConnectionCellDelegate, _MKPlaceTransitIncidentCellDelegate, MKTransitDeparturesCellDelegate>
{
    NSMutableDictionary *_sectionControllers;
    NSMutableSet *_sequencesShowingMultipleDepartures;
    NSMutableDictionary *_multiDepartureSequenceHeightValues;
    NSMutableSet *_animatingSequences;
    NSMapTable *_cachedSectionHeaders;
    _Bool _fetchingTransitInfo;
    _Bool _lastInfoRefreshFailed;
    NSString *_infoRefreshErrorDescription;
    _Bool _hasNoDisplayableDepartures;
    NSMutableArray *_sections;
    NSMutableDictionary *_cachedImages;
    NSMutableDictionary *_cachedSequencesForSection;
    NSMapTable *_cachedDirectionsForSystem;
    _MKPlaceTransitIncidentsController *_incidentsController;
    _Bool _anyIncidentAdvisoryShown;
    NSMutableArray *_shownIncidentTitles;
    _Bool _showDisambiguation;
    _Bool _isFilteredSelection;
    _Bool _allowsTransitLineSelection;
    _Bool _pagingAllowed;
    _Bool _pendingRefresh;
    id <GEOTransitSystem> _filterSystem;
    MKMapItem *_mapItem;
    NSTimer *_cellRefreshTimer;
    NSDate *_departureCutoffDate;
    NSDate *_lastCutoffDateWithValidSchedule;
    id <MKTransitDepaturesViewControllerDelegate> _delegate;
    long long _lastFailureDiagnosis;
}

@property(nonatomic) long long lastFailureDiagnosis; // @synthesize lastFailureDiagnosis=_lastFailureDiagnosis;
@property(nonatomic) __weak id <MKTransitDepaturesViewControllerDelegate> delegate; // @synthesize delegate=_delegate;
@property(nonatomic) _Bool pendingRefresh; // @synthesize pendingRefresh=_pendingRefresh;
@property(nonatomic) _Bool pagingAllowed; // @synthesize pagingAllowed=_pagingAllowed;
@property(retain, nonatomic) NSDate *lastCutoffDateWithValidSchedule; // @synthesize lastCutoffDateWithValidSchedule=_lastCutoffDateWithValidSchedule;
@property(retain, nonatomic) NSTimer *cellRefreshTimer; // @synthesize cellRefreshTimer=_cellRefreshTimer;
@property(retain, nonatomic) MKMapItem *mapItem; // @synthesize mapItem=_mapItem;
@property(readonly, nonatomic) _Bool allowsTransitLineSelection; // @synthesize allowsTransitLineSelection=_allowsTransitLineSelection;
@property(readonly, nonatomic) _Bool isFilteredSelection; // @synthesize isFilteredSelection=_isFilteredSelection;
@property(nonatomic) _Bool showDisambiguation; // @synthesize showDisambiguation=_showDisambiguation;
@property(retain, nonatomic) id <GEOTransitSystem> filterSystem; // @synthesize filterSystem=_filterSystem;
- (void).cxx_destruct;
- (long long)_departureSequenceFrequencyTypeForSection:(long long)arg1;
- (long long)_departureSequenceFrequencyTypeForAllDeparturesSections;
- (int)_transitCategoryForSequence:(id)arg1;
- (int)transitCategoryForFrequencyType:(long long)arg1;
- (int)_transitCategoryForSection:(long long)arg1;
- (int)currentTransitCategory;
- (void)recordIncidentShown:(id)arg1 system:(id)arg2;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (_Bool)tableView:(id)arg1 shouldHighlightRowAtIndexPath:(id)arg2;
- (void)tableView:(id)arg1 didEndDisplayingCell:(id)arg2 forRowAtIndexPath:(id)arg3;
- (void)tableView:(id)arg1 willDisplayCell:(id)arg2 forRowAtIndexPath:(id)arg3;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (id)tableView:(id)arg1 viewForFooterInSection:(long long)arg2;
- (id)tableView:(id)arg1 viewForHeaderInSection:(long long)arg2;
- (double)tableView:(id)arg1 heightForFooterInSection:(long long)arg2;
- (double)tableView:(id)arg1 heightForHeaderInSection:(long long)arg2;
- (double)tableView:(id)arg1 estimatedHeightForFooterInSection:(long long)arg2;
- (double)tableView:(id)arg1 estimatedHeightForHeaderInSection:(long long)arg2;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (double)tableView:(id)arg1 estimatedHeightForRowAtIndexPath:(id)arg2;
- (id)_cellForRowAtIndexPath:(id)arg1;
- (id)_indexPathWithHeader:(id)arg1;
- (id)_indexPathWithoutHeader:(id)arg1;
- (id)_incidentCellForRow:(long long)arg1;
- (id)_connectionCellForRow:(long long)arg1;
- (id)_messageCell;
- (void)_configureDeparturesCell:(id)arg1 forIndexPath:(id)arg2;
- (void)_updateSecondaryTextForHighFrequencyCell:(id)arg1 withSequence:(id)arg2;
- (_Bool)_updateSecondaryTextForOperatingHours:(id)arg1 withSequence:(id)arg2;
- (id)_startEndDatesForSequence:(id)arg1 date:(id)arg2;
- (id)_nextLastDepartureDateForSequence:(id)arg1 afterDate:(id)arg2;
- (_Bool)_isDateLastDeparture:(id)arg1 withNextDepartureDate:(id)arg2 forSequence:(id)arg3;
- (id)_serviceGapDescriptionForDepartureDates:(id)arg1 inSequence:(id)arg2;
- (id)_descriptionForDepartureDate:(id)arg1 canIncludeDate:(_Bool)arg2;
- (id)_timestampFormatterForTimeZoneDisplay:(_Bool)arg1;
- (void)_localeDidChange;
- (double)_maxImageWidthPassingTest:(CDUnknownBlockType)arg1;
- (double)_maxImageWidth;
- (double)_columnCenteringImageWidth;
- (_Bool)_isImageCandidateForColumnCentering:(id)arg1;
- (id)_imageForSystem:(id)arg1;
- (id)_imageForLine:(id)arg1;
- (id)_imageForLine:(id)arg1 size:(long long)arg2;
- (long long)_lineImageSize;
- (id)_imageKeyForLine:(id)arg1 size:(long long)arg2;
- (_Bool)_isCompressed;
- (_Bool)_isCompressedWithTraits:(id)arg1;
- (id)_imageWithArtworkDataSource:(id)arg1;
- (id)_smallerImageWithArtworkDataSource:(id)arg1;
- (id)_viewForFooterInSection:(long long)arg1;
- (id)_viewForHeaderInSection:(long long)arg1;
- (void)timesTappedInDeparturesCell:(id)arg1;
- (void)dragDidEndInDeparturesCell:(id)arg1;
- (void)dragDidBeginInDeparturesCell:(id)arg1;
- (void)incidentButtonSelectedInDeparturesCell:(id)arg1;
- (void)infoButtonSelectedInIncidentCell:(id)arg1;
- (void)infoButtonSelectedInConnectionCell:(id)arg1;
- (id)_pagingPromptForSection:(long long)arg1;
- (_Bool)_sectionHasFooter:(long long)arg1;
- (_Bool)_sectionHasHeader:(long long)arg1;
- (long long)_numberOfRowsInSection:(long long)arg1;
- (id)_controllerForSection:(long long)arg1;
- (id)_directionForSection:(long long)arg1;
- (id)_directionsForSystem:(id)arg1 hasSequencesWithNoDirection:(out _Bool *)arg2;
- (id)_departureSequencesForSection:(long long)arg1;
- (id)_systemForSection:(long long)arg1;
- (id)_systemForSection:(long long)arg1 firstSection:(long long *)arg2;
- (void)_rebuildSections;
- (long long)_sectionsCount;
- (long long)_numberOfSectionsForSystem:(id)arg1;
- (id)_departureSequenceForIndexPath:(id)arg1 outDepartureIndex:(unsigned long long *)arg2 outIsNewLine:(_Bool *)arg3 outNextLineIsSame:(_Bool *)arg4;
- (id)_dominantIncidentForLine:(id)arg1;
- (id)_blockedLines;
- (id)_incidents;
- (id)_departureCutoffDateForSequence:(id)arg1;
- (id)_departureSequenceForIndexPath:(id)arg1;
- (_Bool)_hasIncidentsSection;
- (_Bool)_hasMessageSection;
- (_Bool)_hasConnectionsSection;
- (long long)_sectionTypeForSection:(long long)arg1;
- (void)_toggleShowingMultipleDeparturesForCell:(id)arg1 atIndexPath:(id)arg2;
- (void)_refreshCellsWithCutoffUpdate:(_Bool)arg1;
- (void)_refreshCells;
- (void)_multiSystemRefreshCellsIfNecessary:(id)arg1;
- (_Bool)_isStuckWithExpiredInfo;
- (_Bool)_isInfoExpired;
- (void)_updateScheduleInfoIfNeeded;
- (void)_refresh;
- (void)_refreshTransitInfo;
- (_Bool)_shouldPageSection:(long long)arg1;
- (void)_incrementPageControlValueForSection:(id)arg1;
- (void)_pageControlButtonPressed:(id)arg1;
- (long long)_sectionForIdentifier:(id)arg1;
- (id)_identifierForSection:(long long)arg1;
- (id)_identifierForSequence:(id)arg1;
@property(retain, nonatomic) NSDate *departureCutoffDate; // @synthesize departureCutoffDate=_departureCutoffDate;
- (void)_updateDepartureCutoffDate;
- (double)_heightForFooterInSection:(long long)arg1;
- (double)_heightForRows;
- (id)_separatorColor;
- (void)traitCollectionDidChange:(id)arg1;
- (void)viewDidDisappear:(_Bool)arg1;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLoad;
- (void)dealloc;
- (id)initWithMapItem:(id)arg1 allowTransitLineSelection:(_Bool)arg2;
- (id)initWithMapItem:(id)arg1 allowTransitLineSelection:(_Bool)arg2 filterSystem:(id)arg3;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

