//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <MapKit/MKTableViewCell.h>

@class NSDate, NSLayoutConstraint, NSString, UILabel, UITextView;

__attribute__((visibility("hidden")))
@interface MKTransitIncidentDetailCell : MKTableViewCell
{
    UITextView *_descriptionLabel;
    UILabel *_lastUpdatedLabel;
    NSLayoutConstraint *_descriptionToTopConstraint;
    NSLayoutConstraint *_lastUpdatedToDescriptionConstraint;
    NSDate *_lastUpdated;
}

@property(retain, nonatomic) NSDate *lastUpdated; // @synthesize lastUpdated=_lastUpdated;
- (void).cxx_destruct;
- (void)_updateLastUpdatedLabel;
@property(copy, nonatomic) NSString *incidentDescription;
- (void)didMoveToWindow;
- (void)_contentSizeCategoryDidChange;
- (void)_updateConstraintValues;
- (void)dealloc;
- (void)setConstraints;
- (id)initWithReuseIdentifier:(id)arg1;

@end

