//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSCalendar.h>

@interface NSCalendar (MKExtras)
- (id)_maps_dateStringForDate:(id)arg1 withStyle:(unsigned long long)arg2 useRelativeFormatting:(_Bool)arg3 inTimeZone:(id)arg4;
- (_Bool)_maps_isDateInTomorrow:(id)arg1 inTimeZone:(id)arg2;
- (_Bool)_maps_isDateInToday:(id)arg1 inTimeZone:(id)arg2;
- (id)_maps_offsetDate:(id)arg1 toTimeZone:(id)arg2;
@end

