//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UICollectionViewCell.h>

@class CNQuickActionButton;

__attribute__((visibility("hidden")))
@interface CNQuickActionCell : UICollectionViewCell
{
    CNQuickActionButton *_button;
}

@property(retain, nonatomic) CNQuickActionButton *button; // @synthesize button=_button;
- (void).cxx_destruct;
- (id)initWithFrame:(struct CGRect)arg1;

@end

