//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Photos/PHFetchResult.h>

@class NSArray, NSOrderedSet, NSString;

@interface PHManualFetchResult : PHFetchResult
{
    NSOrderedSet *_objectIDs;
    NSArray *_objects;
    NSString *_identifier;
}

@property(readonly) NSString *identifier; // @synthesize identifier=_identifier;
@property(readonly) NSArray *objects; // @synthesize objects=_objects;
- (void).cxx_destruct;
- (id)description;
- (id)fetchResultWithChangeHandlingValue:(id)arg1;
- (id)fetchUpdatedObjects;
- (unsigned long long)possibleChangesForChange:(id)arg1;
- (void)updateRegistrationForChangeNotificationDeltas;
- (id)objectIDAtIndex:(unsigned long long)arg1;
- (id)fetchedObjectIDs;
- (id)containerIdentifier;
- (long long)collectionFetchType;
- (id)fetchedObjects;
- (id)fetchRequest;
- (void)prefetchObjectsAtIndexes:(id)arg1;
- (id)photoLibrary;
- (id)changeHandlingValueUsingSeedOids:(id)arg1 withChange:(id)arg2 usingManagedObjectContext:(id)arg3;
- (id)changeHandlingKey;
- (id)copyWithOptions:(id)arg1;
- (void)getMediaTypeCounts;
- (unsigned long long)hash;
- (_Bool)isEqual:(id)arg1;
@property(readonly) NSOrderedSet *objectIDs;
- (id)initWithOids:(id)arg1 identifier:(id)arg2 registerIfNeeded:(_Bool)arg3;
- (id)initWithObjects:(id)arg1 identifier:(id)arg2 registerIfNeeded:(_Bool)arg3;
- (id)initWithObjects:(id)arg1;

@end

