//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <AVFoundation/NSObject-Protocol.h>

@class AVWeakReference, NSDictionary;

@protocol AVAssetResourceLoaderRequest <NSObject>
+ (SEL)_selectorForInformingDelegateOfCancellationByFig;
- (_Bool)_shouldInformDelegateOfFigCancellation;
- (void)_performCancellationByClient;
- (NSDictionary *)_requestDictionary;
- (AVWeakReference *)_weakReference;
@end

