//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

#import <AVFoundation/NSCopying-Protocol.h>

@class NSArray, NSURL;

@interface AVCaptureIrisStillImageSettings : NSObject <NSCopying>
{
    long long _uniqueID;
    long long _irisMovieMode;
    NSURL *_irisMovieFileURL;
    NSURL *_irisMovieFileURLForEV0Image;
    NSArray *_irisMovieMetadata;
    NSArray *_irisMovieMetadataForEV0Image;
    long long _flashMode;
    long long _HDRMode;
    _Bool _EV0CaptureEnabled;
    _Bool _autoStillImageStabilizationEnabled;
    _Bool _squareCropEnabled;
    _Bool _previewImageEnabled;
    _Bool _highResolutionStillEnabled;
    unsigned int _shutterSound;
}

@property(nonatomic) unsigned int shutterSound; // @synthesize shutterSound=_shutterSound;
@property(nonatomic) _Bool highResolutionStillEnabled; // @synthesize highResolutionStillEnabled=_highResolutionStillEnabled;
@property(nonatomic) _Bool previewImageEnabled; // @synthesize previewImageEnabled=_previewImageEnabled;
@property(nonatomic) _Bool squareCropEnabled; // @synthesize squareCropEnabled=_squareCropEnabled;
@property(nonatomic) _Bool autoStillImageStabilizationEnabled; // @synthesize autoStillImageStabilizationEnabled=_autoStillImageStabilizationEnabled;
@property(nonatomic) _Bool EV0CaptureEnabled; // @synthesize EV0CaptureEnabled=_EV0CaptureEnabled;
@property(nonatomic) long long HDRMode; // @synthesize HDRMode=_HDRMode;
@property(nonatomic) long long flashMode; // @synthesize flashMode=_flashMode;
@property(copy, nonatomic) NSURL *irisMovieFileURLForEV0Image; // @synthesize irisMovieFileURLForEV0Image=_irisMovieFileURLForEV0Image;
@property(copy, nonatomic) NSURL *irisMovieFileURL; // @synthesize irisMovieFileURL=_irisMovieFileURL;
@property(nonatomic) long long irisMovieMode; // @synthesize irisMovieMode=_irisMovieMode;
@property(readonly) long long uniqueID; // @synthesize uniqueID=_uniqueID;
@property(copy, nonatomic) NSArray *irisMovieMetadataForEV0Image;
@property(copy, nonatomic) NSArray *irisMovieMetadata;
- (id)description;
- (void)dealloc;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)init;
- (id)initWithUniqueID:(long long)arg1;

@end

