//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

#import <UserNotification/NSXPCListenerDelegate-Protocol.h>
#import <UserNotification/UNRemoteNotificationServerDelegate-Protocol.h>
#import <UserNotification/UNSNotificationRegistrarServerProtocol-Protocol.h>

@class NSMapTable, NSMutableDictionary, NSString, NSXPCListener, UNRemoteNotificationServer;
@protocol OS_dispatch_queue;

@interface UNNotificationRegistrarConnectionListener : NSObject <NSXPCListenerDelegate, UNSNotificationRegistrarServerProtocol, UNRemoteNotificationServerDelegate>
{
    NSObject<OS_dispatch_queue> *_queue;
    NSXPCListener *_listener;
    NSMutableDictionary *_connectionsByBundleIdentifier;
    NSMapTable *_bundleIdentifiersByConnection;
    UNRemoteNotificationServer *_removeNotificationServer;
}

- (void)_queue_didReceiveDeviceToken:(id)arg1 forBundleIdentifier:(id)arg2;
- (id)_queue_connectionsForBundleIdentifier:(id)arg1;
- (void)_queue_removeConnectionForAllBundleIdentifiers:(id)arg1;
- (void)_queue_removeConnection:(id)arg1 forBundleIdentifier:(id)arg2;
- (void)_queue_addConnection:(id)arg1 forBundleIdentifier:(id)arg2;
- (void)_removeConnectionForAllBundleIdentifiers:(id)arg1;
- (void)_removeConnection:(id)arg1 forBundleIdentifier:(id)arg2;
- (void)_addConnection:(id)arg1 forBundleIdentifier:(id)arg2;
- (id)_environment;
- (_Bool)_isAllowedToAdministerRemoteNotificationSettings;
- (_Bool)_isAllowedToRegisterForBundleIdentifier:(id)arg1;
- (void)notificationTypesForBundleIdentifier:(id)arg1 withResult:(CDUnknownBlockType)arg2;
- (void)notificationSettingsForBundleIdentifier:(id)arg1 withResult:(CDUnknownBlockType)arg2;
- (void)registerRemoteNotificationTypes:(unsigned long long)arg1 forBundleIdentifier:(id)arg2 withResult:(CDUnknownBlockType)arg3;
- (void)requestTokenForRemoteNotificationsForBundleIdentifier:(id)arg1 withResult:(CDUnknownBlockType)arg2;
- (void)remoteNotificationTypesForBundleIdentifier:(id)arg1 withResult:(CDUnknownBlockType)arg2;
- (void)allowsRemoteNotificationsForBundleIdentifier:(id)arg1 withResult:(CDUnknownBlockType)arg2;
- (void)setAllowsBackgroundRefresh:(_Bool)arg1 forBundleIdentifier:(id)arg2;
- (void)backgroundAppRefreshBundleIdentifierMappingWithResult:(CDUnknownBlockType)arg1;
- (void)registerBadgeSettingForBundleIdentifier:(id)arg1;
- (void)registerNotificationSettings:(id)arg1 forBundleIdentifier:(id)arg2 withResult:(CDUnknownBlockType)arg3;
- (void)invalidateTokenForRemoteNotificationsForBundleIdentifier:(id)arg1;
- (void)setObservingRemoteNotifications:(_Bool)arg1 forBundleIdentifier:(id)arg2;
- (void)didReceiveDeviceToken:(id)arg1 forBundleIdentifier:(id)arg2;
- (_Bool)listener:(id)arg1 shouldAcceptNewConnection:(id)arg2;
- (void)dealloc;
- (id)initWithSystemStateProvider:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

