//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import <DVTInstrumentsUtilities/XRErrorResponder-Protocol.h>

@class NSString;

@interface XRStandardErrorResponder : NSObject <XRErrorResponder>
{
}

+ (void)setDefaultResponder:(id)arg1;
+ (id)defaultResponder;
+ (void)initialize;
- (void)logAnamolousErrorMessageWithFormat:(id)arg1 args:(struct __va_list_tag [1])arg2;
- (void)logAnamolousErrorMessageWithFormat:(id)arg1;
- (unsigned long long)respondToFatalError:(id)arg1 from:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

