//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

__attribute__((visibility("hidden")))
@interface CMTop : NSObject
{
}

+ (id)documentWithContents:(id)arg1 ofReaderClass:(Class)arg2 archiver:(id)arg3 properties:(id)arg4;

@end

