//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class NSMutableDictionary;

__attribute__((visibility("hidden")))
@interface OCIFontState : NSObject
{
    NSMutableDictionary *_replacedFontMap;
}

@property(readonly, nonatomic) NSMutableDictionary *replacedFontMap; // @synthesize replacedFontMap=_replacedFontMap;
- (void)dealloc;
- (id)init;

@end

