//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class PLCloudResourceNode, PLPhotoLibrary;

@interface PLCloudResourceRange : NSObject
{
    unsigned short _category;
    PLPhotoLibrary *_photoLibrary;
    PLCloudResourceNode *_rootNode;
}

@property(readonly, nonatomic) PLCloudResourceNode *rootNode; // @synthesize rootNode=_rootNode;
- (_Bool)validateTreeUsingContext:(id)arg1 errors:(id *)arg2;
- (void)logTreeValidationErrors;
- (unsigned long long)insertCloudAsset:(id)arg1;
- (unsigned long long)removeNodeForAssetWithUuid:(id)arg1;
- (void)traverseSubtreeInOrderFromLocalRoot:(id)arg1 withCallbackBlock:(CDUnknownBlockType)arg2 currentDepth:(int)arg3;
@property(readonly, nonatomic) unsigned short category;
- (void)enumerateNodesInRange:(struct _NSRange)arg1 withBlock:(CDUnknownBlockType)arg2;
- (unsigned long long)totalSizeInRange:(struct _NSRange)arg1 forQualityClass:(unsigned short)arg2;
- (unsigned long long)totalSizeForQualityClass:(unsigned short)arg1;
- (unsigned long long)totalDistanceBetween:(id)arg1 and:(id)arg2;
- (unsigned long long)totalAggregateBetween:(id)arg1 and:(id)arg2 usingVisitorFunction:(CDUnknownBlockType)arg3 usingAggregateFunction:(CDUnknownBlockType)arg4;
@property(readonly, nonatomic) unsigned long long totalAssetCount;
- (id)lowestCommonAncestorBetween:(id)arg1 and:(id)arg2;
- (void)_removeRebalance:(id)arg1;
- (void)_assignSuccessorNode:(id)arg1;
- (void)_insertionRebalanceCaseFive:(id)arg1;
- (void)_insertionRebalanceCaseFour:(id)arg1;
- (void)_insertionRebalanceCaseThree:(id)arg1;
- (void)_insertionRebalanceCaseTwo:(id)arg1;
- (void)_insertionRebalanceCaseOne:(id)arg1;
- (void)_removeTreeNode:(id)arg1;
- (id)_nodeForAssetWithUuid:(id)arg1;
- (void)dealloc;
- (id)initWithBudgetingCategory:(unsigned short)arg1 photoLibrary:(id)arg2;

@end

