//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@interface PLCloudCacheResetMessage : NSObject
{
    _Bool _hardReset;
}

@property(readonly, nonatomic) _Bool hardReset; // @synthesize hardReset=_hardReset;
- (id)initAsHardReset:(_Bool)arg1;

@end

