//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <PhotoLibraryServices/PLCloudService.h>

@interface PLCloudBudgetService : PLCloudService
{
    unsigned long long _lastCacheDeleteRequestBytes;
    long long _lastCacheDeleteRequestTime;
}

- (void)cacheDelete:(id)arg1;
- (void)publishUpdatedBudget;
- (void)activate;
- (id)messageWithCurrentState;
- (unsigned long long)availableBudget;

@end

