//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@interface PLFileUtilities : NSObject
{
}

+ (_Bool)changeFileOwnerToMobileAtPath:(id)arg1 error:(id *)arg2;
+ (_Bool)changeFileOwnerToMobileAtPath:(id)arg1 error:(id *)arg2 usingFileManager:(id)arg3;
+ (_Bool)createDirectoryAtPath:(id)arg1 error:(id *)arg2;
+ (_Bool)createDirectoryAtPath:(id)arg1 error:(id *)arg2 usingFileManager:(id)arg3;
+ (_Bool)hasDiskSpaceToCopyFileAtURL:(id)arg1;
+ (_Bool)stripExtendedAttributesFromFileAtURL:(id)arg1 inDomain:(id)arg2 error:(id *)arg3;
+ (_Bool)copyItemAtURL:(id)arg1 toURL:(id)arg2 error:(id *)arg3;
+ (_Bool)secureMoveItemAtURL:(id)arg1 toURL:(id)arg2 error:(id *)arg3;
+ (_Bool)moveItemAtURL:(id)arg1 toURL:(id)arg2 error:(id *)arg3;
+ (_Bool)_moveItemAtURL:(id)arg1 toURL:(id)arg2 securely:(_Bool)arg3 error:(id *)arg4;
+ (id)fileManager;

@end

