//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSXPCConnection;
@protocol OS_dispatch_queue;

@interface FMDFMIPManager : NSObject
{
    NSXPCConnection *_xpcConnection;
    NSObject<OS_dispatch_queue> *_xpcConnectionCreationQueue;
}

+ (id)sharedInstance;
@property(retain, nonatomic) NSObject<OS_dispatch_queue> *xpcConnectionCreationQueue; // @synthesize xpcConnectionCreationQueue=_xpcConnectionCreationQueue;
@property(retain, nonatomic) NSXPCConnection *xpcConnection; // @synthesize xpcConnection=_xpcConnection;
- (void).cxx_destruct;
- (void)userNotifiedOfWatchActivationLock;
- (void)markPairedDeviceWithUDID:(id)arg1 asMissingWithCompletion:(CDUnknownBlockType)arg2;
- (id)disableFMIPUsingToken:(id)arg1 forPairedDeviceWithUDID:(id)arg2;
- (void)_checkCallingOSUser;
- (id)newErrorForCode:(int)arg1 message:(id)arg2;
- (void)_forceALUpgradeAlertWithCompletion:(CDUnknownBlockType)arg1;
- (void)userNotifiedOfActivationLockForPairedDevices:(id)arg1;
- (void)userNotifiedOfActivationLockForAllPairedDevices;
- (void)setLowBatteryLocateEnabled:(_Bool)arg1 withCompletion:(CDUnknownBlockType)arg2;
- (void)lowBatteryLocateEnabledWithCompletion:(CDUnknownBlockType)arg1;
- (void)initiateLostModeExitAuthWithCompletion:(CDUnknownBlockType)arg1;
- (void)didReceiveLostModeExitAuthToken:(id)arg1;
- (_Bool)needsLostModeExitAuth;
- (void)enableActivationLockWithCompletion:(CDUnknownBlockType)arg1;
- (void)isActivationLockedWithCompletion:(CDUnknownBlockType)arg1;
- (void)isActivationLockEnabledWithCompletion:(CDUnknownBlockType)arg1;
- (void)isActivationLockAllowedWithCompletion:(CDUnknownBlockType)arg1;
- (void)markPairedDeviceWithUDID:(id)arg1 asMissingUsingToken:(id)arg2 withCompletion:(CDUnknownBlockType)arg3;
- (void)markAsMissingSupportedForPairedDeviceWithUDID:(id)arg1 withCompletion:(CDUnknownBlockType)arg2;
- (void)disableFMIPUsingToken:(id)arg1 forPairedDeviceWithUDID:(id)arg2 withCompletion:(CDUnknownBlockType)arg3;
- (id)disableFMIPUsingToken:(id)arg1 inContext:(unsigned long long)arg2;
- (id)enableFMIPInContext:(unsigned long long)arg1;
- (void)didChangeFMIPAccountInfo:(id)arg1;
- (id)fmipAccount;
- (void)fmipAccountWithCompletion:(CDUnknownBlockType)arg1;
- (void)fmipStateWithCompletion:(CDUnknownBlockType)arg1;
- (_Bool)lockdownShouldDisableDevicePairing;
- (_Bool)lockdownShouldDisableDeviceRestore;
- (void)deviceActivationDidSucceed;
- (void)disableLostMode;
- (id)enableLostModeWithInfo:(id)arg1;
- (id)lostModeInfo;
- (_Bool)lostModeIsActive;
- (void)_destroyXPCConnection;
- (id)currentXPCConnection;
- (void)dealloc;
- (id)init;
- (void)disableTouchIDForLostModeWithCompletion:(CDUnknownBlockType)arg1;
- (_Bool)_quickFetchFMIPEnabledstate;

@end

