//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UITableViewController.h>

#import <VUSocialUpload/FlickrPhotoSetTableDelegate-Protocol.h>

@class FlickrPhotoSetManager, NSString;
@protocol FlickrComposeOptionViewDelegate;

@interface FlickrPhotoSetController : UITableViewController <FlickrPhotoSetTableDelegate>
{
    id <FlickrComposeOptionViewDelegate> _delegate;
    FlickrPhotoSetManager *_manager;
    long long _photoSetID;
    NSString *_photoSetTitle;
    long long _selectedIndexRow;
}

@property(nonatomic) long long selectedIndexRow; // @synthesize selectedIndexRow=_selectedIndexRow;
@property(readonly, nonatomic) NSString *photoSetTitle; // @synthesize photoSetTitle=_photoSetTitle;
@property(readonly, nonatomic) long long photoSetID; // @synthesize photoSetID=_photoSetID;
@property(retain, nonatomic) FlickrPhotoSetManager *manager; // @synthesize manager=_manager;
@property(nonatomic) __weak id <FlickrComposeOptionViewDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)tableView:(id)arg1 willDisplayCell:(id)arg2 forRowAtIndexPath:(id)arg3;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (void)reloadData;
- (void)loadView;
- (id)initWithPhotoSetManager:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

