//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import <AppleAccountUI/AAUIAccountRepairRemoteUIDelegate-Protocol.h>
#import <AppleAccountUI/AAUIGenericTermsRemoteUIDelegate-Protocol.h>

@class AAUIAccountRepairRemoteUI, AAUIGenericTermsRemoteUI, ACAccountStore, ACAccountType, NSLock, NSMutableDictionary, NSString, UIViewController;

@interface AAUISignInFlowController : NSObject <AAUIAccountRepairRemoteUIDelegate, AAUIGenericTermsRemoteUIDelegate>
{
    ACAccountStore *_accountStore;
    ACAccountType *_appleAccountType;
    AAUIGenericTermsRemoteUI *_genericTermsRemoteUI;
    AAUIAccountRepairRemoteUI *_accountRepairRemoteUI;
    CDUnknownBlockType _pendingCompletion;
    NSMutableDictionary *_cdpContextsByAccountID;
    NSLock *_cdpContextsByAccountIDLock;
    _Bool _shouldAutomaticallySaveSignInResults;
    UIViewController *_presentingViewController;
}

@property(nonatomic) _Bool shouldAutomaticallySaveSignInResults; // @synthesize shouldAutomaticallySaveSignInResults=_shouldAutomaticallySaveSignInResults;
@property(nonatomic) __weak UIViewController *presentingViewController; // @synthesize presentingViewController=_presentingViewController;
- (void).cxx_destruct;
- (id)_appleAccountType;
- (id)_titleForError:(id)arg1 account:(id)arg2;
- (void)_presentExistingAccountAlert:(id)arg1;
- (void)_presentValidationErrorAlert:(id)arg1 forAccount:(id)arg2 completion:(CDUnknownBlockType)arg3;
- (void)accountRepairRemoteUI:(id)arg1 account:(id)arg2 didFinishWithSuccess:(_Bool)arg3;
- (void)_loadAccountRepairRemoteUIWithAccount:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (void)_showSecondFactorUIForAccount:(id)arg1 loginResponse:(id)arg2 completion:(CDUnknownBlockType)arg3;
- (void)genericTermsRemoteUI:(id)arg1 didFinishWithSuccess:(_Bool)arg2;
- (void)_showGenericTermsUIforAccount:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (void)_presentUnableToSaveAccountAlert;
- (void)_saveAccount:(id)arg1 withAllDataclassesEnabledIfPossibleWithCompletion:(CDUnknownBlockType)arg2;
- (void)_validateCDPStateForAccount:(id)arg1 withCDPContext:(id)arg2 completion:(CDUnknownBlockType)arg3;
- (void)_verifyLoginResponseForiCloudAccount:(id)arg1 withSuccess:(_Bool)arg2 response:(id)arg3 error:(id)arg4 completion:(CDUnknownBlockType)arg5;
- (void)signInWithIDMSAuthenticationResults:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

