//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <EventKitUI/EKCalendarInfo.h>

@interface EKDeclinedCalendarItemInfo : EKCalendarInfo
{
}

- (id)icon;
- (id)description;
- (_Bool)isEditable;
- (_Bool)excludeFromSelectAll;
- (void)setSelected:(_Bool)arg1;
- (id)title;
- (id)init;

@end

