//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UINavigationController.h>

@class EKEvent, EKEventEditor, EKEventStore, NSString, UIColor;
@protocol EKEventEditViewDelegate;

@interface EKEventEditViewController : UINavigationController
{
    EKEventStore *_store;
    EKEvent *_event;
    NSString *_eventId;
    int _transitionForModalViewPresentation;
    id <EKEventEditViewDelegate> _editViewDelegate;
    EKEventEditor *_editor;
    EKEventEditViewController *_strongSelf;
}

+ (void)setDefaultDatesForEvent:(id)arg1;
+ (id)eventEditViewControllerWithEvent:(id)arg1 eventStore:(id)arg2 editViewDelegate:(id)arg3;
@property(retain, nonatomic) EKEventEditViewController *strongSelf; // @synthesize strongSelf=_strongSelf;
@property(retain, nonatomic) EKEventEditor *editor; // @synthesize editor=_editor;
@property(nonatomic) int transitionForModalViewPresentation; // @synthesize transitionForModalViewPresentation=_transitionForModalViewPresentation;
@property(nonatomic) __weak id <EKEventEditViewDelegate> editViewDelegate; // @synthesize editViewDelegate=_editViewDelegate;
- (void).cxx_destruct;
@property(nonatomic) double editorNavBarRightContentInset;
@property(nonatomic) double editorNavBarLeftContentInset;
@property(retain, nonatomic) UIColor *editorBackgroundColor;
- (_Bool)hasUnsavedChanges;
- (_Bool)willPresentDialogOnSave;
- (void)completeAndSave;
- (void)handleTapOutside;
@property(nonatomic) _Bool canHideDoneAndCancelButtons;
@property(nonatomic) _Bool showAttachments;
@property(nonatomic) _Bool scrollToNotes;
- (struct CGSize)preferredContentSize;
- (unsigned long long)supportedInterfaceOrientations;
- (void)_storeChanged:(id)arg1;
- (void)editor:(id)arg1 prepareCalendarItemForEdit:(id)arg2;
- (void)editor:(id)arg1 didCompleteWithAction:(long long)arg2;
- (void)cancelEditing;
- (_Bool)saveWithSpan:(long long)arg1 animated:(_Bool)arg2;
- (void)refreshStartAndEndDates;
@property(retain, nonatomic) EKEvent *event;
@property(retain, nonatomic) EKEventStore *eventStore;
- (void)dealloc;
- (_Bool)shouldAutorotate;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;

@end

