//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <EventKitUI/EKEventDetailItem.h>

@class NSArray;

__attribute__((visibility("hidden")))
@interface EKEventAlarmDetailItem : EKEventDetailItem
{
    unsigned long long _disclosedSubitem;
    NSArray *_alarms;
    _Bool _hasLeaveNowAlarm;
    _Bool _canHaveLeaveNowAlarm;
}

+ (id)_textLabelForIndex:(unsigned long long)arg1;
- (void).cxx_destruct;
- (_Bool)editItemViewControllerShouldShowDetachAlert;
- (_Bool)editItemViewControllerCommit:(id)arg1;
- (id)detailViewControllerWithFrame:(struct CGRect)arg1 forSubitemAtIndex:(unsigned long long)arg2;
- (id)cellForSubitemAtIndex:(unsigned long long)arg1;
- (double)defaultCellHeightForSubitemAtIndex:(unsigned long long)arg1 forWidth:(double)arg2;
- (unsigned long long)numberOfSubitems;
- (_Bool)configureWithCalendar:(id)arg1 preview:(_Bool)arg2;
- (_Bool)_alarmsAreCreatable;
- (_Bool)_alarmsAreEditable;
- (void)reset;
- (void)setEvent:(id)arg1 store:(id)arg2;
- (void)_updateAlarms;

@end

