//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Search/NSObject-Protocol.h>

@class NSArray, NSString;
@protocol PRSApp;

@protocol PRSActionButton <NSObject>

@optional
@property(retain, nonatomic) id <PRSApp> punchout;
@property(nonatomic) _Bool streaming;
@property(retain, nonatomic) NSArray *adam_ids;
@property(retain, nonatomic) NSString *label_itunes;
@property(retain, nonatomic) NSString *label;
@property(retain, nonatomic) NSString *type;
@property(nonatomic) _Bool is_overlay;
@property(retain, nonatomic) NSString *provider;
@end

