//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Search/NSCopying-Protocol.h>
#import <Search/NSObject-Protocol.h>
#import <Search/PRSPredictionSupport-Protocol.h>

@class NSString, NSURL;
@protocol PRSApp;

@protocol PRSBaseResult <NSObject, NSCopying, PRSPredictionSupport>
@property(retain, nonatomic) NSString *section_header;
@property(retain, nonatomic) NSString *templateName;
@property(retain, nonatomic) NSString *fbr;
@property(nonatomic) float resultScore;
@property(retain, nonatomic) NSString *title;
@property(retain, nonatomic) NSString *resultIdentifier;

@optional
@property(retain, nonatomic) id <PRSApp> app;
@property(retain, nonatomic) NSString *bundle_id;
@property(nonatomic) long long max_age;
@property(retain, nonatomic) NSURL *resultURL;
@property(nonatomic) double geoUserSessionStartTime;
@property(retain, nonatomic) NSString *geoUserSessionIDString;
@property(nonatomic) _Bool playable;
@property(retain, nonatomic) NSString *adam_id;
@property(nonatomic) long long media_kind;
@property(nonatomic) long long placement;
@property(retain, nonatomic) NSString *resultBundleID;
@property long long topHitScore;
@property _Bool isQuickGlance;
@property(nonatomic) unsigned long long rank;
@property(nonatomic) unsigned long long score;
@property(retain, nonatomic) NSString *type;
@end

