//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Search/SPFeedback.h>

@class NSArray, NSDictionary;

@interface SPFeedbackRender : SPFeedback
{
    _Bool _leftOfHome;
    double _triggerTimestamp;
    NSDictionary *_renderedZKW;
    NSArray *_renderedZKWMaps;
    NSArray *_hiddentExtResults;
    NSArray *_sections;
}

@property(retain, nonatomic) NSArray *sections; // @synthesize sections=_sections;
@property(nonatomic) _Bool leftOfHome; // @synthesize leftOfHome=_leftOfHome;
@property(retain, nonatomic) NSArray *hiddentExtResults; // @synthesize hiddentExtResults=_hiddentExtResults;
@property(retain, nonatomic) NSArray *renderedZKWMaps; // @synthesize renderedZKWMaps=_renderedZKWMaps;
@property(retain, nonatomic) NSDictionary *renderedZKW; // @synthesize renderedZKW=_renderedZKW;
@property(nonatomic) double triggerTimestamp; // @synthesize triggerTimestamp=_triggerTimestamp;
- (void).cxx_destruct;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)parsecFeedbackFromSession:(id)arg1;

@end

