//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Search/SPFeedback.h>

@interface SPFeedbackAbandonment : SPFeedback
{
    unsigned long long _reason;
}

@property(nonatomic) unsigned long long reason; // @synthesize reason=_reason;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)parsecFeedbackFromSession:(id)arg1;

@end

