//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <ProtocolBuffer/PBCodable.h>

#import <Search/NSCopying-Protocol.h>

@class NSArray, NSMutableOrderedSet, NSString;

@interface SPSearchResultSection : PBCodable <NSCopying>
{
    NSString *_category;
    NSString *_displayIdentifier;
    unsigned int _domain;
    int _flags;
    NSString *_icon;
    NSMutableOrderedSet *_resultSet;
    NSString *_scheme;
    struct {
        unsigned int domain:1;
        unsigned int flags:1;
    } _has;
    _Bool _isGlanceCategory;
    NSArray *_hiddenExtResults;
}

@property(nonatomic) _Bool isGlanceCategory; // @synthesize isGlanceCategory=_isGlanceCategory;
@property(retain, nonatomic) NSArray *hiddenExtResults; // @synthesize hiddenExtResults=_hiddenExtResults;
@property(nonatomic) int flags; // @synthesize flags=_flags;
@property(retain, nonatomic) NSString *scheme; // @synthesize scheme=_scheme;
@property(retain, nonatomic) NSString *category; // @synthesize category=_category;
@property(retain, nonatomic) NSString *displayIdentifier; // @synthesize displayIdentifier=_displayIdentifier;
@property(retain, nonatomic) NSString *icon; // @synthesize icon=_icon;
@property(nonatomic) unsigned int domain; // @synthesize domain=_domain;
- (void).cxx_destruct;
- (void)addHiddenExtResult:(id)arg1;
@property(readonly, nonatomic) _Bool hasResults;
- (_Bool)serialized;
- (unsigned long long)hash;
- (_Bool)isEqual:(id)arg1;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (void)copyTo:(id)arg1;
- (void)serializeTo:(id)arg1;
- (void)writeTo:(id)arg1;
- (_Bool)readFrom:(id)arg1;
- (id)dictionaryRepresentation;
- (id)description;
- (void)removeResultsAtIndex:(unsigned long long)arg1;
- (id)resultsAtIndex:(unsigned long long)arg1;
- (unsigned long long)indexOfResult:(id)arg1;
- (unsigned long long)resultsCount;
- (void)addResults:(id)arg1 atIndex:(unsigned long long)arg2;
- (void)addResults:(id)arg1;
- (void)clearResults;
- (id)resultSet;
- (id)results;
@property(nonatomic) _Bool hasFlags;
@property(readonly, nonatomic) _Bool hasScheme;
@property(readonly, nonatomic) _Bool hasCategory;
@property(readonly, nonatomic) _Bool hasDisplayIdentifier;
@property(readonly, nonatomic) _Bool hasIcon;
@property(nonatomic) _Bool hasDomain;
- (_Bool)hasEquivalentResults:(id)arg1;

@end

