//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Message/MFAuthScheme.h>

@interface MFAPOPAuthScheme : MFAuthScheme
{
}

+ (void)load;
- (_Bool)canAuthenticateAccountClass:(Class)arg1 connection:(id)arg2;
- (id)humanReadableName;
- (id)name;
- (_Bool)requiresPassword;
- (_Bool)hasEncryption;
- (Class)authenticatorClass;
- (Class)connectionClassForAccountClass:(Class)arg1;
- (_Bool)supportsAccountType:(id)arg1;

@end

