//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class MPURemoteApplicationActivity, NSLock;
@protocol MPURemoteApplicationActivityDelegate;

@interface MPURemoteApplicationActivityController : NSObject
{
    MPURemoteApplicationActivity *_currentActivity;
    NSLock *_currentActivityFetchLock;
    _Bool _isObservingActivityStatusChanges;
    id <MPURemoteApplicationActivityDelegate> _delegate;
}

@property(nonatomic) __weak id <MPURemoteApplicationActivityDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)_reloadCurrentActivity;
- (void)_activityStatusDidChangeNotification:(id)arg1;
- (void)_activityHasEndedNotification:(id)arg1;
- (void)_activityHasBegunNotification:(id)arg1;
- (void)endObservingActivityStatusChanges;
- (void)beginObservingActivityStatusChanges;
@property(readonly, nonatomic) MPURemoteApplicationActivity *currentActivity;
- (void)dealloc;
- (id)init;

@end

