//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <TVKit/TVOptionDialogViewController.h>

#import <ATVLegacyContentKit/ATVUpdatable-Protocol.h>

@class NSIndexPath, TVLOptionDialogElement;

@interface TVLOptionDialogViewController : TVOptionDialogViewController <ATVUpdatable>
{
    TVLOptionDialogElement *_optionDialogElement;
    NSIndexPath *_currentFocusedIndexPath;
}

@property(retain, nonatomic) NSIndexPath *currentFocusedIndexPath; // @synthesize currentFocusedIndexPath=_currentFocusedIndexPath;
@property(retain, nonatomic) TVLOptionDialogElement *optionDialogElement; // @synthesize optionDialogElement=_optionDialogElement;
- (void).cxx_destruct;
- (_Bool)tableView:(id)arg1 shouldHandleLongPressForItemAtIndexPath:(id)arg2;
- (void)tableView:(id)arg1 didReceiveLongPressForItemAtIndexPath:(id)arg2;
- (void)tableView:(id)arg1 didReceivePhysicalPlayForItemAtIndexPath:(id)arg2;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (void)tableView:(id)arg1 didUpdateFocusInContext:(id)arg2 withAnimationCoordinator:(id)arg3;
- (id)indexPathForPreferredFocusedViewInTableView:(id)arg1;
- (double)_listWidth;
- (id)_createDataSource;
- (void)updateWithFeedElement:(id)arg1;
- (id)currentFeedElement;
- (void)headerViewImageChanged;
- (void)viewDidLoad;
- (id)initWithOptionDialogElement:(id)arg1;

@end

