//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSDictionary, NSString;

@interface NSObject (AXATV_Extras)
@property(readonly, nonatomic) NSDictionary *_atvaccessibilityITMLSemanticContext;
@property(readonly, nonatomic) NSString *_atvaccessibilityITMLAccessibilityContent;
- (id)_atvaccessibilityAncestorHasAXID:(id)arg1;
- (id)_atvaccessibilityClosestElementAbove:(id)arg1;
- (id)_atvaccessibilityGeometricNearestHeader;
@end

