//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class NSString;

@interface MTLVertexAttribute : NSObject
{
}

+ (id)allocWithZone:(struct _NSZone *)arg1;
+ (id)alloc;

// Remaining properties
@property(readonly, getter=isActive) _Bool active; // @dynamic active;
@property(readonly) unsigned long long attributeIndex; // @dynamic attributeIndex;
@property(readonly) unsigned long long attributeType; // @dynamic attributeType;
@property(readonly) NSString *name; // @dynamic name;

@end

