//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSArray, NSString;

@interface HAPMetadataService : NSObject
{
    _Bool _allowAssociatedService;
    NSString *_name;
    NSString *_svcDescription;
    NSString *_uuidStr;
    NSString *_btleuuidStr;
    NSArray *_mandatoryCharacteristics;
    NSArray *_optionalCharacteristics;
}

@property(nonatomic) _Bool allowAssociatedService; // @synthesize allowAssociatedService=_allowAssociatedService;
@property(retain, nonatomic) NSArray *optionalCharacteristics; // @synthesize optionalCharacteristics=_optionalCharacteristics;
@property(retain, nonatomic) NSArray *mandatoryCharacteristics; // @synthesize mandatoryCharacteristics=_mandatoryCharacteristics;
@property(retain, nonatomic) NSString *btleuuidStr; // @synthesize btleuuidStr=_btleuuidStr;
@property(retain, nonatomic) NSString *uuidStr; // @synthesize uuidStr=_uuidStr;
@property(retain, nonatomic) NSString *svcDescription; // @synthesize svcDescription=_svcDescription;
@property(retain, nonatomic) NSString *name; // @synthesize name=_name;
- (void).cxx_destruct;
- (void)dump;
- (id)description;
- (id)generateDictionary:(id)arg1;
- (id)initWithName:(id)arg1 uuid:(id)arg2 description:(id)arg3 mandatoryCharacteristics:(id)arg4;

@end

