//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import <CoreHAP/HAPKeyStore-Protocol.h>

@class NSString;
@protocol OS_dispatch_queue;

@interface HAPSystemKeychainStore : NSObject <HAPKeyStore>
{
    NSObject<OS_dispatch_queue> *_queue;
    NSString *_activeControllerIdentifier;
}

+ (id)allocWithZone:(struct _NSZone *)arg1;
+ (id)systemStore;
@property(retain, nonatomic) NSString *activeControllerIdentifier; // @synthesize activeControllerIdentifier=_activeControllerIdentifier;
@property(retain, nonatomic) NSObject<OS_dispatch_queue> *queue; // @synthesize queue=_queue;
- (void).cxx_destruct;
- (int)_deleteAllPeripheralIdentifiers;
- (_Bool)deleteAllPeripheralIdentifiers:(id *)arg1;
- (id)getPeripherialIdentifiersAndAccessoryNames;
- (int)_getPeripheralIdentifier:(id *)arg1 forAccessoryName:(id)arg2 protocolVersion:(unsigned long long *)arg3;
- (id)readPeripheralIdentifierForAccessoryName:(id)arg1 protocolVersion:(unsigned long long *)arg2 error:(id *)arg3;
- (int)_deletePeripheralIdentifierForAccessoryName:(id)arg1;
- (_Bool)deletePeripheralIdentifierForAccessoryName:(id)arg1 error:(id *)arg2;
- (_Bool)updatePeripheralIdentifier:(id)arg1 forAccessoryName:(id)arg2 protocolVersion:(unsigned long long)arg3 error:(id *)arg4;
- (int)_savePeripheralIdentifier:(id)arg1 forAccessoryName:(id)arg2 protocolVersion:(unsigned long long)arg3;
- (_Bool)savePeripheralIdentifier:(id)arg1 forAccessoryName:(id)arg2 protocolVersion:(unsigned long long)arg3 error:(id *)arg4;
- (int)_removeKeychainItem:(id)arg1 leaveTombstone:(_Bool)arg2;
- (int)_addKeychainItem:(id)arg1;
- (id)_getKeychainItemsForAccessGroup:(id)arg1 type:(id)arg2 account:(id)arg3 shouldReturnData:(_Bool)arg4 error:(int *)arg5;
- (_Bool)_removeAccessoryKeyForName:(id)arg1;
- (_Bool)removeAllAccessoryKeys:(id *)arg1;
- (_Bool)removeAccessoryKeyForName:(id)arg1 error:(id *)arg2;
- (_Bool)registerAccessoryWithHomeKit:(id)arg1 error:(id *)arg2;
- (int)_savePublicKey:(id)arg1 forAccessoryName:(id)arg2;
- (_Bool)savePublicKey:(id)arg1 forAccessoryName:(id)arg2 error:(id *)arg3;
- (int)_getPublicKey:(id *)arg1 registeredWithHomeKit:(_Bool *)arg2 forAccessoryName:(id)arg3;
- (id)readPublicKeyForAccessoryName:(id)arg1 registeredWithHomeKit:(_Bool *)arg2 error:(id *)arg3;
- (int)_createMetadataSecretKey:(id *)arg1;
- (int)_getMetadataSecretKey:(id *)arg1;
- (_Bool)getMetadataSecretKey:(id *)arg1 error:(id *)arg2;
- (int)_removeControllerKeyPairForIdentifier:(id)arg1 leaveTombstone:(_Bool)arg2;
- (_Bool)removeControllerKeyPairForIdentifier:(id)arg1 leaveTombstone:(_Bool)arg2 error:(id *)arg3;
- (_Bool)getCurrentiCloudIdentifier:(id *)arg1 controllerPairingIdentifier:(id *)arg2 error:(id *)arg3;
- (int)_updateCurrentiCloudIdentifier:(id)arg1 controllerPairingIdentifier:(id)arg2;
- (_Bool)updateCurrentiCloudIdentifier:(id)arg1 controllerPairingIdentifier:(id)arg2 error:(id *)arg3;
- (int)_removeControllerKeyPair;
- (_Bool)removeControllerKeyPairWithError:(id *)arg1;
- (void)updateActiveControllerPairingIdentifier:(id)arg1;
- (_Bool)_getAllAvailableControllerPublicKeys:(id *)arg1 secretKeys:(id *)arg2 userNames:(id *)arg3;
- (_Bool)getAllAvailableControllerPublicKeys:(id *)arg1 secretKeys:(id *)arg2 userNames:(id *)arg3 error:(id *)arg4;
- (_Bool)deserializeKeyPair:(id)arg1 publicKey:(id *)arg2 secretKey:(id *)arg3 error:(id *)arg4;
- (int)_saveKeyPair:(id)arg1 username:(id)arg2 syncable:(_Bool)arg3;
- (_Bool)saveKeyPair:(id)arg1 username:(id)arg2 syncable:(_Bool)arg3 error:(id *)arg4;
- (int)_createControllerPublicKey:(id *)arg1 secretKey:(id *)arg2 keyPair:(id *)arg3 username:(id *)arg4;
- (int)_getControllerPublicKey:(id *)arg1 secretKey:(id *)arg2 keyPair:(id *)arg3 username:(id *)arg4;
- (_Bool)getControllerPublicKey:(id *)arg1 secretKey:(id *)arg2 keyPair:(id *)arg3 username:(id *)arg4 allowCreation:(_Bool)arg5 error:(id *)arg6;
- (_Bool)getControllerKeyPair:(id *)arg1 username:(id *)arg2 error:(id *)arg3;
- (_Bool)getControllerPublicKey:(id *)arg1 secretKey:(id *)arg2 username:(id *)arg3 allowCreation:(_Bool)arg4 error:(id *)arg5;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

