//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class HAPAccessory, NSArray, NSNumber, NSString;

@interface HAPService : NSObject
{
    NSString *_type;
    NSNumber *_instanceID;
    HAPAccessory *_accessory;
    NSArray *_characteristics;
    NSArray *_includedServices;
}

@property(readonly, nonatomic) NSArray *includedServices; // @synthesize includedServices=_includedServices;
@property(retain, nonatomic) NSArray *characteristics; // @synthesize characteristics=_characteristics;
@property(nonatomic) __weak HAPAccessory *accessory; // @synthesize accessory=_accessory;
@property(copy, nonatomic) NSNumber *instanceID; // @synthesize instanceID=_instanceID;
@property(copy, nonatomic) NSString *type; // @synthesize type=_type;
- (void).cxx_destruct;
- (id)characteristicsOfType:(id)arg1;
- (_Bool)isEqualToService:(id)arg1;
- (_Bool)_validateMandatoryCharacteristics;
- (_Bool)_validateServiceCharacteristics;
- (_Bool)_updateCharacteristic:(id)arg1;
- (_Bool)_updateAndValidateCharacteristics;
- (id)description;
- (id)initWithType:(id)arg1 instanceID:(id)arg2;
- (id)initWithType:(id)arg1 instanceID:(id)arg2 parsedCharacteristics:(id)arg3;

@end

