//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <CoreSuggestionsInternals/SGPipelineDissector.h>

@interface SGDetectedAttributeDissector : SGPipelineDissector
{
}

+ (_Bool)isPhoneContext:(id)arg1;
+ (_Bool)isAddressContext:(id)arg1;
+ (void)initialize;
- (id)detailTypeFromPrefix:(id)arg1;
- (id)detailTypeFromPrefix:(id)arg1 detectedLabelPointer:(struct _NSRange *)arg2;
- (id)getLineContaining:(struct _NSRange)arg1 inText:(id)arg2;
- (void)dissectInternal:(id)arg1;
- (id)filterDangerousSigDetections:(id)arg1 onEntity:(id)arg2;
- (id)filterDangerousSigEmailDetections:(id)arg1 onEntity:(id)arg2;
- (id)filterDangerousSigAddressDetections:(id)arg1 onEntity:(id)arg2;
- (id)filterDangerousSigPhoneDetections:(id)arg1 onEntity:(id)arg2;
- (id)detectionFromBodyDDMatch:(id)arg1 onEntity:(id)arg2;
- (id)detectionFromSignatureDDMatch:(id)arg1 onEntity:(id)arg2 detectedLabelRange:(struct _NSRange *)arg3 lastClaimedLabelRange:(struct _NSRange)arg4;

@end

