//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import <CoreSuggestionsInternals/SGReverseTemplateJS-Protocol.h>

@class JSContext, JSVirtualMachine, NSMutableArray, NSString, NSURL, SGAsset, SGReverseTemplatesJSDataDetectors;
@protocol OS_dispatch_queue;

@interface SGReverseTemplateJS : NSObject <SGReverseTemplateJS>
{
    JSVirtualMachine *_jsVM;
    NSMutableArray *_memoryMappedFiles;
    JSContext *_jsContext;
    SGReverseTemplatesJSDataDetectors *_dd;
    SGAsset *_asset;
    NSURL *_assetPath;
    NSString *_localeIdentifier;
    NSObject<OS_dispatch_queue> *_queue;
}

- (void).cxx_destruct;
- (void)emailToOutput:(id)arg1 reply:(CDUnknownBlockType)arg2;
- (void)shouldDownloadFull:(id)arg1 reply:(CDUnknownBlockType)arg2;
- (id)emailToOutput:(id)arg1 setForExceptionTemplates:(id)arg2;
- (_Bool)shouldDownloadFull:(id)arg1;
- (void)holdXpcTransactionForShortDelay;
- (id)loadJSFromASCIIFile:(id)arg1;
- (void)initCurrentAsset;
- (id)processLoadRequestWithFileName:(id)arg1;
- (void)setAssetPath:(id)arg1 locale:(id)arg2;
- (void)freeJSContext;
- (id)getJSContext;
- (id)init;

@end

