//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <WebInspector/RWIProtocolJSONObject.h>

@interface RWIProtocolCSSRegion : RWIProtocolJSONObject
{
}

@property(nonatomic) int nodeId;
@property(nonatomic) long long regionOverset;
- (id)initWithRegionOverset:(long long)arg1 nodeId:(int)arg2;

@end

