//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

#import <SharedWebCredentials/NSXPCListenerDelegate-Protocol.h>
#import <SharedWebCredentials/SWCXPCServer-Protocol.h>

@class NSMutableArray, NSString, NSXPCListener;
@protocol OS_dispatch_source;

@interface SWCManager : NSObject <NSXPCListenerDelegate, SWCXPCServer>
{
    NSMutableArray *_database;
    NSXPCListener *_xpcListener;
    NSMutableArray *_netRequests;
    NSObject<OS_dispatch_source> *_retryTimer;
    NSObject<OS_dispatch_source> *_recheckTimer;
    NSMutableArray *_xpcRequests;
    _Bool _started;
    _Bool _addedAllApps;
    _Bool _allowUnsigned;
    _Bool _redirects;
    _Bool _verifyEV;
}

- (int)_verifyTrust:(struct __SecTrust *)arg1;
- (void)_parseServiceDomainString:(id)arg1 legacy:(_Bool)arg2 service:(id *)arg3 domain:(id *)arg4;
- (id)_appEntitlementsByID:(id)arg1;
- (void)show:(id)arg1 reply:(CDUnknownBlockType)arg2;
- (void)logControl:(id)arg1 reply:(CDUnknownBlockType)arg2;
- (void)addAllAppsWithReply:(CDUnknownBlockType)arg1;
- (void)setService:(id)arg1 app:(id)arg2 domain:(id)arg3 mask:(unsigned int)arg4 flags:(unsigned int)arg5 reply:(CDUnknownBlockType)arg6;
- (void)setService:(id)arg1 app:(id)arg2 domain:(id)arg3 details:(id)arg4 reply:(CDUnknownBlockType)arg5;
- (void)removeService:(id)arg1 app:(id)arg2 domain:(id)arg3 reply:(CDUnknownBlockType)arg4;
- (int)_addService:(id)arg1 app:(id)arg2 domain:(id)arg3;
- (void)addService:(id)arg1 app:(id)arg2 domain:(id)arg3 reply:(CDUnknownBlockType)arg4;
- (void)getInfoForService:(id)arg1 app:(id)arg2 domain:(id)arg3 reply:(CDUnknownBlockType)arg4;
- (void)checkService:(id)arg1 app:(id)arg2 domain:(id)arg3 reply:(CDUnknownBlockType)arg4;
- (void)_connectionInvalidated:(id)arg1;
- (_Bool)listener:(id)arg1 shouldAcceptNewConnection:(id)arg2;
- (void)connection:(id)arg1 didFailWithError:(id)arg2;
- (void)connectionDidFinishLoading:(id)arg1;
- (void)connection:(id)arg1 didReceiveData:(id)arg2;
- (void)connection:(id)arg1 didReceiveResponse:(id)arg2;
- (id)connection:(id)arg1 willSendRequest:(id)arg2 redirectResponse:(id)arg3;
- (void)connection:(id)arg1 willSendRequestForAuthenticationChallenge:(id)arg2;
- (id)_findAppRequestForURLConnection:(id)arg1;
- (void)_completeAppsRequestForURLConnection:(id)arg1 status:(int)arg2 services:(id)arg3;
- (int)_startAppsRequestForDomain:(id)arg1;
- (void)_reorderAppLinks:(id)arg1 domain:(id)arg2;
- (void)_performPeriodicRechecks;
- (void)_schedulePeriodicRechecks;
- (void)_retryDownloads;
- (void)_scheduleRetries;
- (void)_sanitizeDatabase;
- (id)_findService:(id)arg1 app:(id)arg2 domain:(id)arg3;
- (void)removeBundleID:(id)arg1;
- (void)addBundleID:(id)arg1 preApproved:(_Bool)arg2;
- (void)addBundleID:(id)arg1;
- (void)addAllApps;
- (void)addAllAppleApps;
- (int)_saveDatabase;
- (int)_ensureDatabaseLoaded;
- (void)stop;
- (void)start;
- (void)dealloc;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

