//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class TVSImageDecorator, _TVSDecoratorRequest;

@interface TVSImageProxy : NSObject
{
    _Bool _cacheOnLoad;
    _Bool _imageAvailable;
    _Bool _loadSynchronouslyIfCached;
    _Bool _writeToAssetLibrary;
    _Bool _isLoading;
    id _object;
    id _imageLoader;
    TVSImageDecorator *_decorator;
    CDUnknownBlockType _completionHandler;
    CDUnknownBlockType _writeCompletionHandler;
    long long _groupType;
    id _requestToken;
    _TVSDecoratorRequest *_decoratorRequestToken;
}

+ (id)_imageDecoratorQueue;
@property(nonatomic) _Bool isLoading; // @synthesize isLoading=_isLoading;
@property(retain, nonatomic) _TVSDecoratorRequest *decoratorRequestToken; // @synthesize decoratorRequestToken=_decoratorRequestToken;
@property(retain, nonatomic) id requestToken; // @synthesize requestToken=_requestToken;
@property(nonatomic) long long groupType; // @synthesize groupType=_groupType;
@property(nonatomic) _Bool writeToAssetLibrary; // @synthesize writeToAssetLibrary=_writeToAssetLibrary;
@property(nonatomic) _Bool loadSynchronouslyIfCached; // @synthesize loadSynchronouslyIfCached=_loadSynchronouslyIfCached;
@property(nonatomic, getter=isImageAvailable) _Bool imageAvailable; // @synthesize imageAvailable=_imageAvailable;
@property(copy, nonatomic) CDUnknownBlockType writeCompletionHandler; // @synthesize writeCompletionHandler=_writeCompletionHandler;
@property(copy, nonatomic) CDUnknownBlockType completionHandler; // @synthesize completionHandler=_completionHandler;
@property(retain, nonatomic) TVSImageDecorator *decorator; // @synthesize decorator=_decorator;
@property(nonatomic) _Bool cacheOnLoad; // @synthesize cacheOnLoad=_cacheOnLoad;
@property(retain, nonatomic) id imageLoader; // @synthesize imageLoader=_imageLoader;
@property(readonly, nonatomic) id object; // @synthesize object=_object;
- (void).cxx_destruct;
- (void)cancel;
- (id)_imageAssetPathWithAssetKey:(id)arg1;
- (id)_decoratedImageAssetPath;
- (id)_originalImageAssetPath;
- (id)_decoratedImageAssetKey;
- (id)_originalImageAssetKey;
- (id)_imageLoaderKey;
- (id)_assetKeyWithImageLoaderKey:(id)arg1 decoratorIdentifier:(id)arg2;
- (id)_decoratorIdentifier;
- (id)_extensionForImage:(id)arg1;
- (void)_imageDidWriteHandler:(id)arg1;
- (void)_completeImageLoadWithImage:(id)arg1 imagePath:(id)arg2 error:(id)arg3 assetKey:(id)arg4 expiryDate:(id)arg5;
- (void)_decorateAndWriteImage:(id)arg1 imagePath:(id)arg2 scaleToSize:(struct CGSize)arg3 cropToFit:(_Bool)arg4 scalingResult:(unsigned long long)arg5 assetKey:(id)arg6 expiryDate:(id)arg7;
- (void)load;
@property(readonly, nonatomic) struct CGSize expectedSize;
- (unsigned long long)hash;
- (_Bool)isEqual:(id)arg1;
- (id)description;
- (void)dealloc;
- (id)initWithObject:(id)arg1 imageLoader:(id)arg2 groupType:(long long)arg3;

@end

