//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <TVServices/TVSImageScaleDecorator.h>

@class UIColor;

@interface TVSImageOutlineDecorator : TVSImageScaleDecorator
{
    UIColor *_outlineColor;
    struct UIEdgeInsets _outlineWidths;
}

+ (id)decoratorWithOutlineColor:(id)arg1 outlineWidths:(struct UIEdgeInsets)arg2;
@property(readonly, nonatomic) struct UIEdgeInsets outlineWidths; // @synthesize outlineWidths=_outlineWidths;
@property(readonly, copy, nonatomic) UIColor *outlineColor; // @synthesize outlineColor=_outlineColor;
- (void).cxx_destruct;
- (void)_drawInScaledContext:(struct CGContext *)arg1;
- (id)decoratorIdentifier;
- (id)initWithOutlineColor:(id)arg1 outlineWidths:(struct UIEdgeInsets)arg2;

@end

