//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString, TVSPreferences;

@interface TVSMusicSettings : NSObject
{
    TVSPreferences *_musicPreferences;
    _Bool _shouldLimitAdTracking;
    _Bool _musicAdvertisingIdentifierNeedsReset;
    NSString *_musicAdvertisingIdentifier;
}

+ (id)sharedInstance;
@property(copy, nonatomic) NSString *musicAdvertisingIdentifier; // @synthesize musicAdvertisingIdentifier=_musicAdvertisingIdentifier;
@property(nonatomic) _Bool musicAdvertisingIdentifierNeedsReset; // @synthesize musicAdvertisingIdentifierNeedsReset=_musicAdvertisingIdentifierNeedsReset;
@property(readonly, nonatomic) _Bool shouldLimitAdTracking; // @synthesize shouldLimitAdTracking=_shouldLimitAdTracking;
- (void).cxx_destruct;
- (void)_updateValues;
- (id)init;

@end

