//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString;

@interface TVSPlaybackState : NSObject
{
    NSString *_name;
}

+ (id)scanning;
+ (id)playing;
+ (id)paused;
+ (id)loading;
+ (id)stopped;
@property(retain, nonatomic) NSString *name; // @synthesize name=_name;
- (void).cxx_destruct;
- (id)description;
- (_Bool)isEqual:(id)arg1;
- (id)initWithName:(id)arg1;
- (id)init;

@end

