//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSArray, NSDictionary, NSMutableArray, NSString;
@protocol TVSMediaItem;

@interface TVSPlaylist : NSObject
{
    NSMutableArray *_historyItems;
    NSMutableArray *_playQueueItems;
    NSMutableArray *_playQueueHistory;
    NSMutableArray *_trackList;
    NSMutableArray *_shuffledItems;
    unsigned long long _activeListIndex;
    NSArray *_activeList;
    NSArray *_upcomingItems;
    _Bool _isCollection;
    _Bool _windowed;
    _Bool _shuffleEnabled;
    _Bool _skipExplicit;
    _Bool _playQueueActive;
    _Bool _bracketChanges;
    NSObject<TVSMediaItem> *_currentMediaItem;
    NSObject<TVSMediaItem> *_nextMediaItem;
    NSObject<TVSMediaItem> *_previousMediaItem;
    long long _endAction;
    unsigned long long _currentIndex;
    unsigned long long _count;
    NSString *_name;
    long long _repeatMode;
    NSDictionary *_changeContext;
    unsigned long long _upcomingItemsLimit;
    unsigned long long _historyLimit;
    CDUnknownBlockType _playQueueModificationHandler;
    unsigned long long _upNextIndex;
}

+ (id)keyPathsForValuesAffectingValueForKey:(id)arg1;
+ (_Bool)automaticallyNotifiesObserversForKey:(id)arg1;
@property(retain, nonatomic) NSMutableArray *playQueueHistory; // @synthesize playQueueHistory=_playQueueHistory;
@property(readonly, nonatomic) unsigned long long upNextIndex; // @synthesize upNextIndex=_upNextIndex;
@property(readonly, nonatomic) unsigned long long activeListIndex; // @synthesize activeListIndex=_activeListIndex;
@property(readonly, nonatomic) NSArray *activeList; // @synthesize activeList=_activeList;
@property(copy, nonatomic) CDUnknownBlockType playQueueModificationHandler; // @synthesize playQueueModificationHandler=_playQueueModificationHandler;
@property(nonatomic) _Bool bracketChanges; // @synthesize bracketChanges=_bracketChanges;
@property(nonatomic) _Bool playQueueActive; // @synthesize playQueueActive=_playQueueActive;
@property(readonly, nonatomic) NSArray *playQueueItems; // @synthesize playQueueItems=_playQueueItems;
@property(nonatomic) unsigned long long historyLimit; // @synthesize historyLimit=_historyLimit;
@property(copy, nonatomic) NSArray *historyItems; // @synthesize historyItems=_historyItems;
@property(nonatomic) unsigned long long upcomingItemsLimit; // @synthesize upcomingItemsLimit=_upcomingItemsLimit;
@property(retain, nonatomic) NSDictionary *changeContext; // @synthesize changeContext=_changeContext;
@property(nonatomic) _Bool skipExplicit; // @synthesize skipExplicit=_skipExplicit;
@property(nonatomic) long long repeatMode; // @synthesize repeatMode=_repeatMode;
@property(readonly, nonatomic) _Bool shuffleEnabled; // @synthesize shuffleEnabled=_shuffleEnabled;
@property(retain, nonatomic) NSString *name; // @synthesize name=_name;
@property(nonatomic) _Bool windowed; // @synthesize windowed=_windowed;
@property(nonatomic) unsigned long long count; // @synthesize count=_count;
@property(nonatomic) unsigned long long currentIndex; // @synthesize currentIndex=_currentIndex;
@property(nonatomic) long long endAction; // @synthesize endAction=_endAction;
@property(readonly, nonatomic) NSArray *trackList; // @synthesize trackList=_trackList;
@property(retain, nonatomic) NSObject<TVSMediaItem> *previousMediaItem; // @synthesize previousMediaItem=_previousMediaItem;
@property(retain, nonatomic) NSObject<TVSMediaItem> *nextMediaItem; // @synthesize nextMediaItem=_nextMediaItem;
@property(retain, nonatomic) NSObject<TVSMediaItem> *currentMediaItem; // @synthesize currentMediaItem=_currentMediaItem;
- (void).cxx_destruct;
- (void)_addItemToHistory:(id)arg1;
- (void)clearHistoryItems;
- (void)addItemsToUpNext:(id)arg1;
- (void)removeItemFromPlayQueueAtIndexes:(id)arg1;
- (void)removeItemFromPlayQueueAtIndex:(unsigned long long)arg1;
- (void)insertItemsInPlayQueue:(id)arg1 atIndexes:(id)arg2;
- (void)insertItemInPlayQueue:(id)arg1 atIndex:(unsigned long long)arg2;
- (void)_initializePlayQueueIfNecessary:(_Bool)arg1;
- (void)addItemsToPlayQueue:(id)arg1 withAction:(long long)arg2 isCollection:(_Bool)arg3;
- (void)addItemToPlayQueue:(id)arg1 withAction:(long long)arg2;
- (void)clearPlayQueueItems;
- (void)_updatePlayQueueActive;
@property(readonly, nonatomic) NSArray *upcomingItems;
- (void)removeItemsAtIndexes:(id)arg1;
- (void)removeItemAtIndex:(unsigned long long)arg1;
- (void)insertItems:(id)arg1 atIndexes:(id)arg2;
- (void)insertItem:(id)arg1 atIndex:(unsigned long long)arg2;
- (void)addItems:(id)arg1;
- (void)addItem:(id)arg1;
@property(readonly, nonatomic) _Bool supportsRepeat;
- (void)_updateShuffleFill;
- (void)_shuffle:(_Bool)arg1;
- (void)setShuffleEnabled:(_Bool)arg1 preserveCurrentItem:(_Bool)arg2;
@property(readonly, nonatomic) _Bool supportsShuffle;
- (void)_updateCurrent:(_Bool)arg1 andNextItems:(_Bool)arg2 withContext:(id)arg3;
- (_Bool)moreItemsAvailable:(long long)arg1;
- (_Bool)_isMediaItemExplicit:(id)arg1;
- (unsigned long long)_previousActiveListIndex;
- (unsigned long long)_nextActiveListIndex;
- (void)changeMedia:(long long)arg1 withContext:(id)arg2;
- (void)changeMedia:(long long)arg1;
- (id)initWithMediaItems:(id)arg1 index:(long long)arg2 isCollection:(_Bool)arg3;
- (id)init;

@end

