//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import <TVServices/CBCentralManagerDelegate-Protocol.h>
#import <TVServices/CBPairingAgentDelegate-Protocol.h>
#import <TVServices/CBPeripheralDelegate-Protocol.h>

@class CBCentralManager, CBPeripheral, NSArray, NSMutableDictionary, NSString;

@interface TVSPeripheralManager : NSObject <CBCentralManagerDelegate, CBPeripheralDelegate, CBPairingAgentDelegate>
{
    CBCentralManager *_centralManager;
    NSMutableDictionary *_discoveredCBPeripherals;
    NSMutableDictionary *_connectedCBPeripherals;
    NSString *_factoryBDAddress;
    CBPeripheral *_peripheralBeingConnected;
    _Bool _autoConnectWithImmediateProximityPeripheralsEnabled;
    _Bool _factoryPairingEnabled;
    CDUnknownBlockType _unpairBlock;
}

+ (id)sharedInstance;
@property(copy, nonatomic) CDUnknownBlockType unpairBlock; // @synthesize unpairBlock=_unpairBlock;
@property(nonatomic) _Bool factoryPairingEnabled; // @synthesize factoryPairingEnabled=_factoryPairingEnabled;
@property(nonatomic) _Bool autoConnectWithImmediateProximityPeripheralsEnabled; // @synthesize autoConnectWithImmediateProximityPeripheralsEnabled=_autoConnectWithImmediateProximityPeripheralsEnabled;
- (void).cxx_destruct;
- (void)_removePreviousBluetoothRemoteIfNeeded:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (void)_startScanning;
- (id)_retrievePairedRemoteBDAddress;
- (void)_unblockConnectionQueueForPeripheral:(id)arg1;
- (id)_pairingDialogTitleFromPeer:(id)arg1;
- (void)_presentPairingPasskeyChallengeForPeripheral:(id)arg1;
- (void)_presentPairingPasskeyForPeripheral:(id)arg1 withPasskey:(id)arg2;
- (void)_connectPeripheral:(id)arg1;
- (_Bool)_shouldConnectDerpModePeripheral:(id)arg1 withAdvertisementData:(id)arg2;
- (void)readBatteryLevelForPeripheral:(id)arg1;
- (void)stopScanning;
- (void)startScanning;
@property(readonly, nonatomic) NSArray *pairedPeripherals;
@property(readonly, nonatomic) NSArray *connectedPeripherals;
@property(readonly, nonatomic) NSArray *discoveredPeripherals;
- (void)unpairPeripheral:(id)arg1;
- (void)disconnectPeripheral:(id)arg1;
- (void)connectPeripheral:(id)arg1;
- (void)peripheral:(id)arg1 didModifyServices:(id)arg2;
- (void)peripheral:(id)arg1 didUpdateValueForCharacteristic:(id)arg2 error:(id)arg3;
- (void)peripheral:(id)arg1 didDiscoverCharacteristicsForService:(id)arg2 error:(id)arg3;
- (void)peripheral:(id)arg1 didDiscoverServices:(id)arg2;
- (void)centralManager:(id)arg1 didUpdatePeripheralConnectionState:(id)arg2;
- (void)centralManager:(id)arg1 didDisconnectPeripheral:(id)arg2 error:(id)arg3;
- (void)centralManager:(id)arg1 didFailToConnectPeripheral:(id)arg2 error:(id)arg3;
- (void)centralManager:(id)arg1 didConnectPeripheral:(id)arg2;
- (void)centralManager:(id)arg1 didDiscoverPeripheral:(id)arg2 advertisementData:(id)arg3 RSSI:(id)arg4;
- (void)centralManagerDidUpdateState:(id)arg1;
- (void)pairingAgent:(id)arg1 peerDidRequestPairing:(id)arg2 type:(long long)arg3 passkey:(id)arg4;
- (void)pairingAgent:(id)arg1 peerDidUnpair:(id)arg2;
- (void)pairingAgent:(id)arg1 peerDidFailToCompletePairing:(id)arg2 error:(id)arg3;
- (void)pairingAgent:(id)arg1 peerDidCompletePairing:(id)arg2;
- (void)dealloc;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

