//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIViewController.h>

#import <TVMLKit/TVOneupViewDataSource-Protocol.h>
#import <TVMLKit/TVOneupViewDelegate-Protocol.h>

@class IKViewElement, NSArray, NSString, TVOneupView;

__attribute__((visibility("hidden")))
@interface _TVOneupTemplateController : UIViewController <TVOneupViewDelegate, TVOneupViewDataSource>
{
    _Bool _allowsZooming;
    unsigned long long _transition;
    TVOneupView *_oneupView;
    IKViewElement *_oneupElement;
    NSArray *_lockupElements;
    NSArray *_modes;
    long long _autoHighlightIndex;
    NSString *_previousAutoHighlightIdentifier;
}

@property(copy, nonatomic) NSString *previousAutoHighlightIdentifier; // @synthesize previousAutoHighlightIdentifier=_previousAutoHighlightIdentifier;
@property(nonatomic) long long autoHighlightIndex; // @synthesize autoHighlightIndex=_autoHighlightIndex;
@property(nonatomic) _Bool allowsZooming; // @synthesize allowsZooming=_allowsZooming;
@property(copy, nonatomic) NSArray *modes; // @synthesize modes=_modes;
@property(copy, nonatomic) NSArray *lockupElements; // @synthesize lockupElements=_lockupElements;
@property(retain, nonatomic) IKViewElement *oneupElement; // @synthesize oneupElement=_oneupElement;
@property(nonatomic) __weak TVOneupView *oneupView; // @synthesize oneupView=_oneupView;
@property(nonatomic) unsigned long long transition; // @synthesize transition=_transition;
- (void).cxx_destruct;
- (void)_dispatchEventOfType:(unsigned long long)arg1 forItemAtIndex:(unsigned long long)arg2;
- (id)_imgElementFromLockup:(id)arg1;
- (void)_configureView:(id)arg1 withItemAtIndex:(unsigned long long)arg2;
- (unsigned long long)_allowedModesFromModes:(id)arg1 allowsZooming:(_Bool)arg2;
- (void)_updateWithViewElement:(id)arg1 update:(_Bool)arg2;
- (void)oneupView:(id)arg1 didPlayItemAtIndex:(unsigned long long)arg2;
- (void)oneupView:(id)arg1 didSelectItemAtIndex:(unsigned long long)arg2;
- (void)oneupView:(id)arg1 didFocusItemAtIndex:(unsigned long long)arg2;
- (id)oneupView:(id)arg1 supplementaryViewForItemAtIndex:(unsigned long long)arg2;
- (long long)oneupView:(id)arg1 contentModeForItemAtIndex:(unsigned long long)arg2;
- (id)oneupView:(id)arg1 viewForItemAtIndex:(unsigned long long)arg2;
- (long long)numberOfItemsInOneupView:(id)arg1;
- (void)loadView;
- (void)didReceiveMemoryWarning;
@property(readonly, nonatomic) unsigned long long oneupViewTransition;
- (void)updateWithShowcaseLockupElements:(id)arg1 focusedIndex:(long long)arg2 update:(_Bool)arg3;
- (void)updateWithOneElement:(id)arg1;
- (id)initWithOneupElement:(id)arg1;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

