//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <TVMLKit/JSExport-Protocol.h>

@class NSDictionary, NSString, TVJSSKProduct;

@protocol TVJSSKPayment <JSExport>
+ (id)paymentWithProduct:(TVJSSKProduct *)arg1;
@property(copy, nonatomic) NSDictionary *requestParameters;
@property(copy, nonatomic) NSString *partnerTransactionIdentifier;
@property(copy, nonatomic) NSString *partnerIdentifier;
@property(nonatomic) _Bool simulatesAskToBuyInSandbox;
@property(copy, nonatomic) NSString *applicationUsername;
@property(nonatomic) long long quantity;
@property(copy, nonatomic) NSString *requestData;
@property(copy, nonatomic) NSString *productIdentifier;
@end

