//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class CAContext, CALayer, NSString;

@interface PUIProgressWindow : NSObject
{
    _Bool _weCreatedTheContext;
    CAContext *_context;
    struct CGSize _displaySize;
    struct CGSize _framebufferSize;
    float _displayScale;
    float _displayOrientation;
    _Bool _sideways;
    _Bool _renderWithIOSurface;
    float _currentProgress;
    struct CGImage *_appleLogo;
    double _progressXDelta;
    double _progressYDelta;
    double _progressWidth;
    _Bool _forceInverted;
    _Bool _white;
    _Bool _showsProgressBar;
    CALayer *_progressLayer;
    _Bool _showPluginName;
    CALayer *_pluginNameLayer;
    NSString *_pluginName;
    CALayer *_layer;
}

+ (_Bool)_usesPreBoardAppearance;
+ (void)setUsesPreBoardAppearance;
@property(readonly, nonatomic) CALayer *layer; // @synthesize layer=_layer;
- (void).cxx_destruct;
- (struct CGImage *)_createImageWithName:(const char *)arg1 scale:(int)arg2 displayHeight:(int)arg3;
- (void)drawLayer:(id)arg1 inContext:(struct CGContext *)arg2;
- (void)_drawPluginNameLayerInContext:(struct CGContext *)arg1;
- (void)_drawProgressLayerInContext:(struct CGContext *)arg1;
- (void)_layoutScreen;
- (int)_nanoMaterial;
- (_Bool)_isNano;
- (unsigned long long)_nanoDeviceType;
- (const char *)_appleTVProductSuffix;
- (const char *)_productSuffix;
- (void)setPluginName:(id)arg1;
- (void)setProgressValue:(float)arg1;
- (void)setVisible:(_Bool)arg1;
- (void)_updateIOSurface;
- (void)_createLayer;
- (void)_createContext;
- (void)_collectDisplayInfo;
- (void)dealloc;
- (id)initWithOptions:(unsigned long long)arg1 contextLevel:(float)arg2 appearance:(long long)arg3;
- (id)initWithProgressBarVisibility:(_Bool)arg1 createContext:(_Bool)arg2 contextLevel:(float)arg3 appearance:(long long)arg4;
- (id)initWithProgressBarVisibility:(_Bool)arg1 level:(float)arg2 forceInverted:(_Bool)arg3;
- (id)initWithProgressBarVisibility:(_Bool)arg1 context:(id)arg2;
- (id)initWithProgressBarVisibility:(_Bool)arg1 level:(float)arg2;
- (id)initWithProgressBarVisibility:(_Bool)arg1;
- (id)initWithForceInverted:(_Bool)arg1;
- (id)init;

@end

