//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSMutableArray.h>

@interface NSMutableArray (PreferencesAdditions)
- (void)ps_insertObjectsFromArray:(id)arg1 afterObject:(id)arg2;
- (void)ps_insertObject:(id)arg1 afterObject:(id)arg2;
@end

