//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class SSFamilyCircle;

@interface SSFamilyCircleResponse : NSObject
{
    SSFamilyCircle *_familyCircle;
}

@property(retain, nonatomic) SSFamilyCircle *familyCircle; // @synthesize familyCircle=_familyCircle;

@end

