//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class ISPurchaseReceipt, NSDate;

@interface SSPurchaseReceipt : NSObject
{
    ISPurchaseReceipt *_purchaseReceipt;
}

+ (void)getReceiptPathWithCompletionBlock:(CDUnknownBlockType)arg1;
- (void).cxx_destruct;
@property(readonly) NSDate *expirationDate;
@property(readonly) _Bool isRevoked;
@property(readonly) _Bool isVPPLicensed;
- (id)initWithContainerPath:(id)arg1;
- (id)initWithContentsOfFile:(id)arg1;

@end

