//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <CoreData/NSSQLAdapter.h>

@class NSString;

__attribute__((visibility("hidden")))
@interface NSSQLiteAdapter : NSSQLAdapter
{
    NSString *_dbpath;
    struct __CFDictionary *_cachedDeleteTriggersByEntity;
}

- (id)generateSQLStatmentForSourcesAndOrderKeysForDestination:(id)arg1 inManyToMany:(id)arg2;
- (id)generateSQLStatmentForSourcesAndOrderKeysForDestination:(id)arg1 inToMany:(id)arg2;
- (id)generateDeleteStatementsForRequest:(id)arg1 resultObject:(id *)arg2 inContext:(id)arg3 error:(id *)arg4;
- (_Bool)generateTriggerForEntity:(id)arg1 alreadyCreated:(struct __CFDictionary *)arg2 correlations:(struct __CFDictionary *)arg3 fragments:(id)arg4 error:(id *)arg5;
- (id)generateTriggerStatementsForEntity:(id)arg1 usingRelationshipCleanupSQL:(id)arg2 error:(id *)arg3;
- (id)createCleanupSQLForRelationship:(id)arg1 existing:(struct __CFDictionary *)arg2 correlationTableTriggers:(struct __CFDictionary *)arg3 error:(id *)arg4;
- (_Bool)generateCorrelationTableTriggerStatementsForRelationship:(id)arg1 existing:(struct __CFDictionary *)arg2 correlationTableTriggers:(struct __CFDictionary *)arg3 error:(id *)arg4;
- (_Bool)supportsCorrelatedSubqueries;
- (id)sqliteVersion;
- (Class)statementClass;
- (id)type;
- (id)typeStringForColumn:(id)arg1;
- (id)typeStringForSQLType:(unsigned int)arg1;
- (id)pathnameForDatabase;
- (id)newConnection;
- (id)createConnection;
- (void)dealloc;
- (id)initWithSQLCore:(id)arg1;

@end

