//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <VectorKit/VKFeatureMarker.h>

@interface VKPolygonFeatureMarker : VKFeatureMarker
{
    CDStruct_8ede0f48 *_polygonFeature;
}

- (id)name;
- (id)initWithFeature:(CDStruct_8ede0f48 *)arg1;

@end

