//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

__attribute__((visibility("hidden")))
@interface VKRunningCurve : NSObject
{
    CDStruct_86193286 _p0;
    double _t0;
    CDStruct_86193286 _p1;
    double _t1;
    CDStruct_86193286 _pu;
    double _tu;
    struct {
        double mb[4][3];
    } _mb;
    _Bool _mbValid;
}

- (id).cxx_construct;
- (CDStruct_86193286)stateAtTime:(double)arg1;
- (_Bool)hasStateAtTime:(double)arg1;
- (void)appendPosition:(struct VKPoint)arg1 atTime:(double)arg2;
- (void)dealloc;
- (void)reset;
- (id)init;

@end

