//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

#import <VectorKit/VKAnimationRunner-Protocol.h>
#import <VectorKit/VKCameraControllerDelegate-Protocol.h>
#import <VectorKit/VKCameraDelegate-Protocol.h>
#import <VectorKit/VKWorldDelegate-Protocol.h>

@class NSArray, NSMutableArray, NSString, VKCamera, VKDispatch, VKLayoutContext, VKScene, VKWorld;
@protocol MDMapControllerDelegate, MDRenderTarget;

__attribute__((visibility("hidden")))
@interface VKScreenCanvas : NSObject <VKWorldDelegate, VKAnimationRunner, VKCameraControllerDelegate, VKCameraDelegate>
{
    VKDispatch *_dispatch;
    VKWorld *_world;
    VKCamera *_camera;
    VKScene *_scene;
    VKLayoutContext *_layoutContext;
    id <MDRenderTarget> _displayTarget;
    _Bool _needsLayout;
    unsigned int _wantsLayout;
    unsigned int _needsRepaint;
    _Bool _userIsGesturing;
    _Bool _iconsShouldAlignToPixels;
    NSMutableArray *_cameraControllers;
    float _debugFramesPerSecond;
    _Bool _rendersInBackground;
    NSMutableArray *_animations[2];
    _Bool _isInBackground;
    _Bool _isHidden;
    struct VKEdgeInsets _edgeInsets;
    struct VKEdgeInsets _fullyOccludedEdgeInsets;
    struct VKEdgeInsets _labelEdgeInsets;
    _Bool _deallocing;
    _Bool _needsInitialization;
    struct unique_ptr<md::RenderQueue, std::__1::default_delete<md::RenderQueue>> _renderQueue;
    struct MapCamera *_mapCamera;
    struct RenderTree *_mapScene;
    Matrix_5173352a _bgColor;
    id <MDMapControllerDelegate> _mapDelegate;
}

@property(readonly, nonatomic) NSArray *cameraControllers; // @synthesize cameraControllers=_cameraControllers;
@property(readonly, nonatomic) Matrix_5173352a bgColor; // @synthesize bgColor=_bgColor;
@property(readonly, nonatomic) _Bool needsInitialization; // @synthesize needsInitialization=_needsInitialization;
@property(nonatomic) id <MDMapControllerDelegate> mapDelegate; // @synthesize mapDelegate=_mapDelegate;
@property(nonatomic) struct VKEdgeInsets fullyOccludedEdgeInsets; // @synthesize fullyOccludedEdgeInsets=_fullyOccludedEdgeInsets;
@property(nonatomic) _Bool iconsShouldAlignToPixels; // @synthesize iconsShouldAlignToPixels=_iconsShouldAlignToPixels;
@property(readonly, nonatomic) VKCamera *camera; // @synthesize camera=_camera;
@property(nonatomic) float debugFramesPerSecond; // @synthesize debugFramesPerSecond=_debugFramesPerSecond;
@property(readonly, nonatomic) VKWorld *world; // @synthesize world=_world;
- (id).cxx_construct;
- (void).cxx_destruct;
- (void)didReceiveMemoryWarning:(_Bool)arg1 beAggressive:(_Bool)arg2;
- (shared_ptr_3fff3c66)stylesheet;
- (shared_ptr_750cb28c)styleForFeature:(id)arg1;
- (id)roadMarkersForSelectionAtScreenPoint:(struct CGPoint)arg1;
- (id)featureMarkerAtScreenPoint:(struct CGPoint)arg1;
- (id)buildingMarkerAtScreenPoint:(struct CGPoint)arg1;
- (void)edgeInsetsDidEndAnimating;
- (void)edgeInsetsWillBeginAnimating;
@property(nonatomic) _Bool rendersInBackground;
- (void)cameraControllerDidFinishInitialTrackingAnimation:(id)arg1;
- (void)cameraController:(id)arg1 canZoomOutDidChange:(_Bool)arg2;
- (void)cameraController:(id)arg1 canZoomInDidChange:(_Bool)arg2;
- (id)cameraController:(id)arg1 presentationForAnnotation:(id)arg2;
- (void)cameraController:(id)arg1 flyoverModeWillChange:(int)arg2;
- (void)cameraController:(id)arg1 flyoverModeDidChange:(int)arg2;
- (void)cameraController:(id)arg1 canEnter3DModeDidChange:(_Bool)arg2;
- (void)cameraController:(id)arg1 didBecomePitched:(_Bool)arg2;
- (void)cameraController:(id)arg1 didChangeRegionAnimated:(_Bool)arg2;
- (void)cameraController:(id)arg1 willChangeRegionAnimated:(_Bool)arg2;
- (void)cameraControllerDidChangeCameraState:(id)arg1;
- (void)cameraController:(id)arg1 requestsDisplayRate:(long long)arg2;
- (void)removeCameraController:(id)arg1;
- (void)addCameraController:(id)arg1;
@property(nonatomic) struct VehicleState vehicleState;
@property(nonatomic) unsigned char targetDisplay;
@property(nonatomic, getter=isGesturing) _Bool gesturing;
- (void)cameraDidChange:(id)arg1;
- (void)animationDidResume:(id)arg1;
- (void)animationDidStop:(id)arg1;
- (void)runOrAdoptAnimation:(id)arg1 run:(_Bool)arg2;
- (void)runAnimation:(id)arg1;
- (void)worldDisplayDidChange:(id)arg1;
- (void)worldLayoutDidChange:(id)arg1;
- (void)_queueUpdateDisplayLinkStatus;
- (void)setContentsScale:(double)arg1;
- (void)forceLayout;
- (void)resetRenderQueue:(shared_ptr_06328420)arg1;
- (void)updateCameraForFrameResize;
- (void)didPresent;
- (void)layoutRenderQueue:(shared_ptr_06328420)arg1;
- (void)gglWillDrawWithTimestamp;
- (void)animateWithTimestamp:(double)arg1;
@property(nonatomic) struct VKEdgeInsets labelEdgeInsets;
@property(nonatomic) struct VKEdgeInsets edgeInsets;
- (void)updateWithTimestamp:(double)arg1;
- (void)didEnterBackground;
- (void)willEnterForeground;
- (_Bool)currentSceneRequiresMSAA;
- (void)setNeedsDisplay;
- (void)setNeedsLayout;
- (_Bool)isHidden;
- (void)setHidden:(_Bool)arg1;
- (_Bool)updateDisplayLinkStatus;
- (_Bool)wantsTimerTick;
- (_Bool)wantsRender;
- (_Bool)canRender;
- (void)clearSceneIsEffectivelyHidden:(_Bool)arg1;
- (void)transferAnimationsTo:(id)arg1;
- (void)adoptAnimation:(id)arg1;
- (void)dealloc;
- (void)initializeWithRenderer:(struct GLRenderer *)arg1;
- (id)initWithTarget:(id)arg1 device:(const shared_ptr_807ec9ac *)arg2 inBackground:(_Bool)arg3;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

