//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

#import <UserNotificationServices/UNSNotificationRegistrarConnectionObserver-Protocol.h>

@class NSString;
@protocol UNSRemoteNotificationRegistrarDelegate;

@interface UNSRemoteNotificationRegistrar : NSObject <UNSNotificationRegistrarConnectionObserver>
{
    NSString *_bundleIdentifier;
    id <UNSRemoteNotificationRegistrarDelegate> _delegate;
}

+ (void)setAllowsBackgroundRefresh:(_Bool)arg1 forBundleIdentifier:(id)arg2;
+ (id)backgroundAppRefreshBundleIdentifierMapping;
+ (void)backgroundAppRefreshBundleIdentifierMappingWithResult:(CDUnknownBlockType)arg1;
@property(nonatomic) id <UNSRemoteNotificationRegistrarDelegate> delegate; // @synthesize delegate=_delegate;
@property(copy) NSString *bundleIdentifier; // @synthesize bundleIdentifier=_bundleIdentifier;
- (void)didReceiveDeviceToken:(id)arg1 forBundleIdentifier:(id)arg2;
- (unsigned long long)remoteNotificationTypes;
- (void)remoteNotificationTypesWithResult:(CDUnknownBlockType)arg1;
- (void)registerRemoteNotificationTypes:(unsigned long long)arg1 withResult:(CDUnknownBlockType)arg2;
- (void)allowsRemoteNotificationsWithResult:(CDUnknownBlockType)arg1;
- (_Bool)allowsRemoteNotifications;
- (void)invalidateTokenForRemoteNotifications;
- (void)requestTokenForRemoteNotificationsWithResult:(CDUnknownBlockType)arg1;
- (void)dealloc;
- (id)initWithBundleIdentifier:(id)arg1;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

