//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class NSString;

@interface UNSUserNotificationRegistrar : NSObject
{
    NSString *_bundleIdentifier;
}

@property(copy) NSString *bundleIdentifier; // @synthesize bundleIdentifier=_bundleIdentifier;
- (void)registerBadgeSetting;
- (unsigned long long)userNotificationTypes;
- (void)userNotificationTypesWithResult:(CDUnknownBlockType)arg1;
- (id)userNotificationSettings;
- (void)invalidateTokenForRemoteNotifications;
- (void)requestTokenForRemoteNotificationsWithResult:(CDUnknownBlockType)arg1;
- (void)registerUserNotificationSettings:(id)arg1 withResult:(CDUnknownBlockType)arg2;
- (void)userNotificationSettingsWithResult:(CDUnknownBlockType)arg1;
- (void)dealloc;
- (id)initWithBundleIdentifier:(id)arg1;
- (id)init;

@end

