//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class HMDHomeManager, NSArray, NSMutableArray, NSMutableDictionary;

@interface HMDPendingCloudSyncTransactions : NSObject
{
    _Bool _uploadInProgress;
    NSMutableDictionary *_pendingTransactionDictionary;
    NSMutableArray *_deltaTransactions;
    HMDHomeManager *_homeManager;
}

+ (_Bool)isValidRequestTypeKey:(id)arg1;
+ (id)requestToIndentityTypeMapping;
+ (id)convertSaveReasonToTransationReason:(id)arg1;
@property(readonly, nonatomic) __weak HMDHomeManager *homeManager; // @synthesize homeManager=_homeManager;
@property(retain, nonatomic) NSMutableArray *deltaTransactions; // @synthesize deltaTransactions=_deltaTransactions;
@property(nonatomic) _Bool uploadInProgress; // @synthesize uploadInProgress=_uploadInProgress;
@property(retain, nonatomic) NSMutableDictionary *pendingTransactionDictionary; // @synthesize pendingTransactionDictionary=_pendingTransactionDictionary;
- (void).cxx_destruct;
- (void)removePendingTransactionsForHome:(id)arg1;
@property(readonly, nonatomic) NSArray *transactions;
- (void)_fixupPendingTransactions;
- (void)_loadTransactions:(id)arg1;
- (void)addTransaction:(id)arg1;
- (void)_addTransaction:(id)arg1 reason:(id)arg2 identities:(id)arg3;
- (id)identitiesWithHome:(id)arg1 reason:(id)arg2;
@property(readonly, nonatomic) unsigned long long count;
- (void)stopUploadAndResume;
- (void)stopUploadAndClean;
- (void)startUpload;
- (void)reset;
- (id)initWithTransaction:(id)arg1 homeManager:(id)arg2;
- (id)init;

@end

