//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <SAObjects/SABaseCommand.h>

#import <SAObjects/SAAceCommand-Protocol.h>
#import <SAObjects/SAAceSerializable-Protocol.h>
#import <SAObjects/SAClientBoundCommand-Protocol.h>
#import <SAObjects/SAServerBoundCommand-Protocol.h>

@class NSArray, NSString;
@protocol SAAceSerializable;

@interface SAAceDeferredObject : SABaseCommand <SAAceSerializable, SAAceCommand, SAClientBoundCommand, SAServerBoundCommand>
{
}

+ (id)aceDeferredObjectWithDictionary:(id)arg1 context:(id)arg2;
+ (id)aceDeferredObject;
- (_Bool)requiresResponse;
@property(retain, nonatomic) id <SAAceSerializable> value;
@property(copy, nonatomic) NSString *key;
@property(copy, nonatomic) NSArray *callbacks; // @dynamic callbacks;
@property(copy, nonatomic) NSString *appId; // @dynamic appId;
- (id)encodedClassName;
- (id)groupIdentifier;

// Remaining properties
@property(copy, nonatomic) NSString *aceId; // @dynamic aceId;
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(copy, nonatomic) NSString *refId; // @dynamic refId;
@property(readonly) Class superclass;

@end

