//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <SAObjects/SADomainCommand.h>

@class NSString;

@interface SACFAbstractClientCommand : SADomainCommand
{
}

+ (id)abstractClientCommandWithDictionary:(id)arg1 context:(id)arg2;
+ (id)abstractClientCommand;
- (_Bool)requiresResponse;
@property(copy, nonatomic) NSString *jsScript;
@property(copy, nonatomic) NSString *jsParameters;
@property(copy, nonatomic) NSString *domain;
- (id)encodedClassName;
- (id)groupIdentifier;

@end

