//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <ProtocolBuffer/PBCodable.h>

#import <HealthDaemon/NSCopying-Protocol.h>

@class NSData, NSString;

@interface HDCodableProvenance : PBCodable <NSCopying>
{
    NSData *_deviceUUID;
    NSString *_originBuild;
    NSString *_originDevice;
    NSData *_sourceUUID;
    NSString *_sourceVersion;
}

@property(retain, nonatomic) NSString *sourceVersion; // @synthesize sourceVersion=_sourceVersion;
@property(retain, nonatomic) NSData *deviceUUID; // @synthesize deviceUUID=_deviceUUID;
@property(retain, nonatomic) NSData *sourceUUID; // @synthesize sourceUUID=_sourceUUID;
@property(retain, nonatomic) NSString *originDevice; // @synthesize originDevice=_originDevice;
@property(retain, nonatomic) NSString *originBuild; // @synthesize originBuild=_originBuild;
- (void).cxx_destruct;
- (void)mergeFrom:(id)arg1;
- (unsigned long long)hash;
- (_Bool)isEqual:(id)arg1;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (void)copyTo:(id)arg1;
- (void)writeTo:(id)arg1;
- (_Bool)readFrom:(id)arg1;
- (id)dictionaryRepresentation;
- (id)description;
@property(readonly, nonatomic) _Bool hasSourceVersion;
@property(readonly, nonatomic) _Bool hasDeviceUUID;
@property(readonly, nonatomic) _Bool hasSourceUUID;
@property(readonly, nonatomic) _Bool hasOriginDevice;
@property(readonly, nonatomic) _Bool hasOriginBuild;
- (id)decodedDeviceUUID;
- (id)decodedSourceUUID;

@end

