//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import <HealthDaemon/NSCopying-Protocol.h>
#import <HealthDaemon/NSSecureCoding-Protocol.h>

@class NSNumber, NSString;

@interface HDDataOriginProvenance : NSObject <NSSecureCoding, NSCopying>
{
    long long _syncProvenance;
    NSString *_deviceModel;
    NSString *_buildNumber;
    NSNumber *_sourceID;
    NSNumber *_deviceID;
    NSString *_sourceVersion;
}

+ (_Bool)supportsSecureCoding;
+ (id)dataProvenanceWithSyncProvenance:(long long)arg1 deviceModel:(id)arg2 buildNumber:(id)arg3 sourceID:(id)arg4 deviceID:(id)arg5 sourceVersion:(id)arg6;
@property(retain, nonatomic) NSString *sourceVersion; // @synthesize sourceVersion=_sourceVersion;
@property(retain, nonatomic) NSNumber *deviceID; // @synthesize deviceID=_deviceID;
@property(retain, nonatomic) NSNumber *sourceID; // @synthesize sourceID=_sourceID;
@property(copy, nonatomic) NSString *buildNumber; // @synthesize buildNumber=_buildNumber;
@property(copy, nonatomic) NSString *deviceModel; // @synthesize deviceModel=_deviceModel;
@property(nonatomic) long long syncProvenance; // @synthesize syncProvenance=_syncProvenance;
- (void).cxx_destruct;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)description;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (_Bool)isEqual:(id)arg1;
- (_Bool)isValid;
- (unsigned long long)hash;

@end

