//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSFileManager, NSString;

@interface HDDemoData : NSObject
{
    NSString *_baselineDemoDataPath;
    NSString *_demoDataPath;
    NSFileManager *_fileManager;
}

+ (id)demoDataDirectory;
- (void).cxx_destruct;
- (id)_directoryPath;
- (_Bool)_createAndPopulateDemoDataDirectoryIfNeeded;
- (_Bool)_baselineDataDemoAvailable;
- (id)initWithProfile:(id)arg1;

@end

