//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface HDNanoSyncRequestContext : NSObject
{
    _Bool _pullRequest;
    CDUnknownBlockType _completion;
}

+ (id)requestContextWithCompletion:(CDUnknownBlockType)arg1 pullRequest:(_Bool)arg2;
@property(readonly, nonatomic, getter=isPullRequest) _Bool pullRequest; // @synthesize pullRequest=_pullRequest;
@property(readonly, copy, nonatomic) CDUnknownBlockType completion; // @synthesize completion=_completion;
- (void).cxx_destruct;

@end

