//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class HDSourceEntity, NSString;

@interface HDSourceRevision : NSObject
{
    HDSourceEntity *_sourceEntity;
    NSString *_sourceRevision;
}

@property(readonly, nonatomic) NSString *sourceRevision; // @synthesize sourceRevision=_sourceRevision;
@property(readonly, nonatomic) HDSourceEntity *sourceEntity; // @synthesize sourceEntity=_sourceEntity;
- (void).cxx_destruct;
- (id)initWithSource:(id)arg1 sourceRevision:(id)arg2;

@end

