//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <HealthDaemon/HDQueryServer.h>

@interface HDStatisticsQueryServer : HDQueryServer
{
    unsigned long long _statisticsOptions;
    unsigned long long _mergeStrategy;
}

@property(readonly, nonatomic) unsigned long long mergeStrategy; // @synthesize mergeStrategy=_mergeStrategy;
@property(readonly, nonatomic) unsigned long long statisticsOptions; // @synthesize statisticsOptions=_statisticsOptions;
- (id)_statisticsForDataType:(id)arg1 restrictedSourceIdentifier:(id)arg2 filter:(id)arg3 error:(id *)arg4;
- (void)_queue_fetchAndDeliverStatistics;
- (void)_queue_start;
- (id)_quantityType;
- (id)initWithQueryUUID:(id)arg1 dataObject:(id)arg2 clientProxy:(id)arg3 client:(id)arg4 delegate:(id)arg5 healthDaemon:(id)arg6;

@end

