//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@interface CPDocumentAndData : NSObject
{
    struct CGPDFDocument *document;
    struct __CFData *sourceData;
}

@property(retain) struct __CFData *sourceData; // @synthesize sourceData;
@property(retain) struct CGPDFDocument *document; // @synthesize document;
- (void)dealloc;

@end

