//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <SetupAssistantUI/NSObject-Protocol.h>

@class UINavigationController, UIViewController;
@protocol BuddyControllerDelegate;

@protocol BuddyController <NSObject>
- (void)setDelegate:(id <BuddyControllerDelegate>)arg1;

@optional
+ (void)skip;
+ (_Bool)controllerNeedsToRun;
- (_Bool)shouldSuppressExtendedInitializationActivityIndicator;
- (void)performExtendedInitializationWithCompletion:(void (^)(_Bool))arg1;
- (void)removeFromNavHierarchyOf:(UINavigationController *)arg1;
- (UIViewController *)viewController;
- (void)willDisplayStartOver;
- (_Bool)shouldAllowStartOver;
- (void)startOver;
- (_Bool)controllerAllowsNavigatingBack;
- (void)controllerWasPopped;
@end

