//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <ProtocolBuffer/PBCodable.h>

#import <GeoServices/NSCopying-Protocol.h>

@class NSMutableArray, NSString;

@interface GEOActiveTileSet : PBCodable <NSCopying>
{
    CDStruct_d66e66b9 *_availableTiles;
    unsigned long long _availableTilesCount;
    unsigned long long _availableTilesSpace;
    NSString *_baseURL;
    NSString *_localizationURL;
    int _scale;
    NSMutableArray *_sentinelTiles;
    int _size;
    int _style;
    NSMutableArray *_supportedLanguages;
    unsigned int _timeToLiveSeconds;
    int _updateBehavior;
    unsigned int _version;
    struct {
        unsigned int timeToLiveSeconds:1;
        unsigned int updateBehavior:1;
    } _has;
}

@property(retain, nonatomic) NSMutableArray *supportedLanguages; // @synthesize supportedLanguages=_supportedLanguages;
@property(retain, nonatomic) NSString *localizationURL; // @synthesize localizationURL=_localizationURL;
@property(retain, nonatomic) NSMutableArray *sentinelTiles; // @synthesize sentinelTiles=_sentinelTiles;
@property(nonatomic) unsigned int timeToLiveSeconds; // @synthesize timeToLiveSeconds=_timeToLiveSeconds;
@property(nonatomic) unsigned int version; // @synthesize version=_version;
@property(nonatomic) int size; // @synthesize size=_size;
@property(nonatomic) int scale; // @synthesize scale=_scale;
@property(nonatomic) int style; // @synthesize style=_style;
@property(retain, nonatomic) NSString *baseURL; // @synthesize baseURL=_baseURL;
- (void)mergeFrom:(id)arg1;
- (unsigned long long)hash;
- (_Bool)isEqual:(id)arg1;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (void)copyTo:(id)arg1;
- (void)writeTo:(id)arg1;
- (_Bool)readFrom:(id)arg1;
- (id)dictionaryRepresentation;
- (id)description;
@property(nonatomic) _Bool hasUpdateBehavior;
@property(nonatomic) int updateBehavior; // @synthesize updateBehavior=_updateBehavior;
- (id)supportedLanguageAtIndex:(unsigned long long)arg1;
- (unsigned long long)supportedLanguagesCount;
- (void)addSupportedLanguage:(id)arg1;
- (void)clearSupportedLanguages;
@property(readonly, nonatomic) _Bool hasLocalizationURL;
- (id)sentinelTileAtIndex:(unsigned long long)arg1;
- (unsigned long long)sentinelTilesCount;
- (void)addSentinelTile:(id)arg1;
- (void)clearSentinelTiles;
- (void)setAvailableTiles:(CDStruct_d66e66b9 *)arg1 count:(unsigned long long)arg2;
- (CDStruct_d66e66b9)availableTilesAtIndex:(unsigned long long)arg1;
- (void)addAvailableTiles:(CDStruct_d66e66b9)arg1;
- (void)clearAvailableTiles;
@property(readonly, nonatomic) CDStruct_d66e66b9 *availableTiles;
@property(readonly, nonatomic) unsigned long long availableTilesCount;
@property(nonatomic) _Bool hasTimeToLiveSeconds;
@property(readonly, nonatomic) _Bool hasBaseURL;
- (void)dealloc;
- (void)_resetBestLanguage;
- (_Bool)isEquivalentTileSet:(id)arg1;
- (id)_bestLanguageWithOverrideLocale:(id)arg1;
- (id)dataForGenericTileType:(int)arg1 configuration:(id)arg2;
- (_Bool)isAvailableForTileKey:(const struct _GEOTileKey *)arg1;
- (unsigned int)largestZoomLevelLEQ:(unsigned int)arg1 inRect:(CDStruct_90e2a262)arg2;
- (unsigned int)maximumZoomLevelForMapPoint:(CDStruct_c3b9c2ee)arg1;
- (unsigned int)maximumZoomLevelInRect:(CDStruct_90e2a262)arg1;
- (unsigned int)minimumZoomLevelInRect:(CDStruct_90e2a262)arg1;

@end

