//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <GeoServices/GEOCompletionItem-Protocol.h>

@class GEOPDAutocompleteEntry;

@protocol GEOCompletionItemPrivate <GEOCompletionItem>
@property(readonly, nonatomic, getter=_placeDataAutocompleteEntry) GEOPDAutocompleteEntry *placeDataAutocompleteEntry;
@end

