//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <ProtocolBuffer/PBCodable.h>

#import <GeoServices/NSCopying-Protocol.h>

@interface GEONavigationGuidanceState : PBCodable <NSCopying>
{
    int _guidanceLevel;
    int _navigationState;
    int _trackedTransportType;
    _Bool _shouldSuppressCellularDataAlerts;
    struct {
        unsigned int guidanceLevel:1;
        unsigned int navigationState:1;
        unsigned int trackedTransportType:1;
        unsigned int shouldSuppressCellularDataAlerts:1;
    } _has;
}

+ (int)routeGuidanceLevelForLocation:(id)arg1 route:(id)arg2 withCurrentGuidanceLevel:(int)arg3 ignoreTimeCriterion:(_Bool)arg4;
+ (int)routeGuidanceLevelForLocation:(id)arg1 route:(id)arg2 withCurrentGuidanceLevel:(int)arg3;
+ (_Bool)_currentTimeInsideTrackingRegionForRoute:(id)arg1 location:(id)arg2;
+ (_Bool)_currentLocationInsideTrackingRegionForRoute:(id)arg1 location:(id)arg2;
+ (_Bool)_currentLocationInsideTurnByTurnRegionForRoute:(id)arg1 location:(id)arg2;
@property(nonatomic) _Bool shouldSuppressCellularDataAlerts; // @synthesize shouldSuppressCellularDataAlerts=_shouldSuppressCellularDataAlerts;
- (void)mergeFrom:(id)arg1;
- (unsigned long long)hash;
- (_Bool)isEqual:(id)arg1;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (void)copyTo:(id)arg1;
- (void)writeTo:(id)arg1;
- (_Bool)readFrom:(id)arg1;
- (id)dictionaryRepresentation;
- (id)description;
@property(nonatomic) _Bool hasShouldSuppressCellularDataAlerts;
@property(nonatomic) _Bool hasGuidanceLevel;
@property(nonatomic) int guidanceLevel; // @synthesize guidanceLevel=_guidanceLevel;
@property(nonatomic) _Bool hasNavigationState;
@property(nonatomic) int navigationState; // @synthesize navigationState=_navigationState;
@property(nonatomic) _Bool hasTrackedTransportType;
@property(nonatomic) int trackedTransportType; // @synthesize trackedTransportType=_trackedTransportType;
- (id)initWithGuidanceLevel:(int)arg1;
- (id)initWithTransportType:(int)arg1;

@end

