//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <ProtocolBuffer/PBCodable.h>

#import <GeoServices/GEOTransitNamedItem-Protocol.h>
#import <GeoServices/NSCopying-Protocol.h>

@class GEOPBTransitArtwork, GEOPBTransitLineDisplayHints, GEOStyleAttributes, NSString;

@interface GEOPBTransitLine : PBCodable <GEOTransitNamedItem, NSCopying>
{
    unsigned long long _muid;
    CDStruct_43c37391 *_operatingHours;
    unsigned long long _operatingHoursCount;
    unsigned long long _operatingHoursSpace;
    GEOPBTransitArtwork *_artwork;
    GEOPBTransitLineDisplayHints *_displayHints;
    int _guidanceSnappingType;
    NSString *_lineColor;
    unsigned int _lineIndex;
    GEOPBTransitArtwork *_modeArtwork;
    NSString *_nameDisplayString;
    int _preferredDepartureTimeStyle;
    GEOStyleAttributes *_styleAttributes;
    unsigned int _systemIndex;
    struct {
        unsigned int muid:1;
        unsigned int guidanceSnappingType:1;
        unsigned int lineIndex:1;
        unsigned int preferredDepartureTimeStyle:1;
        unsigned int systemIndex:1;
    } _has;
}

@property(retain, nonatomic) NSString *nameDisplayString; // @synthesize nameDisplayString=_nameDisplayString;
@property(retain, nonatomic) GEOPBTransitLineDisplayHints *displayHints; // @synthesize displayHints=_displayHints;
@property(retain, nonatomic) GEOStyleAttributes *styleAttributes; // @synthesize styleAttributes=_styleAttributes;
@property(nonatomic) unsigned int systemIndex; // @synthesize systemIndex=_systemIndex;
@property(retain, nonatomic) NSString *lineColor; // @synthesize lineColor=_lineColor;
@property(nonatomic) unsigned long long muid; // @synthesize muid=_muid;
@property(retain, nonatomic) GEOPBTransitArtwork *modeArtwork; // @synthesize modeArtwork=_modeArtwork;
@property(retain, nonatomic) GEOPBTransitArtwork *artwork; // @synthesize artwork=_artwork;
@property(nonatomic) unsigned int lineIndex; // @synthesize lineIndex=_lineIndex;
- (void)mergeFrom:(id)arg1;
@property(readonly) unsigned long long hash;
- (_Bool)isEqual:(id)arg1;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (void)copyTo:(id)arg1;
- (void)writeTo:(id)arg1;
- (_Bool)readFrom:(id)arg1;
- (id)dictionaryRepresentation;
@property(readonly, copy) NSString *description;
@property(readonly, nonatomic) _Bool hasNameDisplayString;
@property(readonly, nonatomic) _Bool hasDisplayHints;
- (void)setOperatingHours:(CDStruct_43c37391 *)arg1 count:(unsigned long long)arg2;
- (CDStruct_43c37391)operatingHoursAtIndex:(unsigned long long)arg1;
- (void)addOperatingHours:(CDStruct_43c37391)arg1;
- (void)clearOperatingHours;
@property(readonly, nonatomic) CDStruct_43c37391 *operatingHours;
@property(readonly, nonatomic) unsigned long long operatingHoursCount;
@property(readonly, nonatomic) _Bool hasStyleAttributes;
@property(nonatomic) _Bool hasPreferredDepartureTimeStyle;
@property(nonatomic) int preferredDepartureTimeStyle; // @synthesize preferredDepartureTimeStyle=_preferredDepartureTimeStyle;
@property(nonatomic) _Bool hasSystemIndex;
@property(readonly, nonatomic) _Bool hasLineColor;
@property(nonatomic) _Bool hasGuidanceSnappingType;
@property(nonatomic) int guidanceSnappingType; // @synthesize guidanceSnappingType=_guidanceSnappingType;
@property(nonatomic) _Bool hasMuid;
@property(readonly, nonatomic) _Bool hasModeArtwork;
@property(readonly, nonatomic) _Bool hasArtwork;
@property(nonatomic) _Bool hasLineIndex;
- (void)dealloc;
- (id)geoTransitLineWithSystem:(id)arg1;
- (id)bestName;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly) Class superclass;

@end

