//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class GEOPowerAssertion, NSArray, NSData, NSMapTable, NSMutableArray, NSString;
@protocol OS_dispatch_queue;

@interface GEOResourceLoader : NSObject
{
    NSString *_directory;
    NSString *_additionalDirectoryToConsider;
    NSMutableArray *_resourcesToLoad;
    CDUnknownBlockType _completionHandler;
    long long _numberOfDownloadsInProgress;
    long long _numberOfCopiesInProgress;
    NSMutableArray *_loadedResources;
    _Bool _canceled;
    NSString *_baseURLString;
    unsigned long long _maxConcurrentLoads;
    NSArray *_resourceInfos;
    NSData *_auditToken;
    _Bool _allowResumingPartialDownloads;
    NSMapTable *_inProgressResourceDownloads;
    GEOPowerAssertion *_powerAssertion;
    NSObject<OS_dispatch_queue> *_workQueue;
    NSObject<OS_dispatch_queue> *_callbackQueue;
}

+ (Class)resourceLoadOperationClass;
@property(retain, nonatomic) NSData *auditToken; // @synthesize auditToken=_auditToken;
@property(readonly, nonatomic) NSArray *loadedResources; // @synthesize loadedResources=_loadedResources;
- (void)cancel;
- (void)_writeResourceToDisk:(id)arg1 withData:(id)arg2 orExistingPathOnDisk:(id)arg3 allowCreatingHardLink:(_Bool)arg4 checksum:(id)arg5 completionHandler:(CDUnknownBlockType)arg6 callbackQueue:(id)arg7;
- (void)_loadNextResource;
- (_Bool)_establishHardLinkIfPossibleForResource:(id)arg1 toResource:(id)arg2 error:(id *)arg3;
- (void)startWithCompletionHandler:(CDUnknownBlockType)arg1 callbackQueue:(id)arg2;
- (void)_cleanup;
- (void)dealloc;
- (id)initWithTargetDirectory:(id)arg1 baseURLString:(id)arg2 resources:(id)arg3 maximumConcurrentLoads:(unsigned long long)arg4 additionalDirectoryToConsider:(id)arg5;

@end

