//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <ProtocolBuffer/PBCodable.h>

#import <GeoServices/NSCopying-Protocol.h>

@class GEOTraitsTransitScheduleTimeRange;

@interface GEOTraitsTransitScheduleModeFilter : PBCodable <NSCopying>
{
    double _additionalTimeLimit;
    unsigned int _numAdditionalDepartures;
    GEOTraitsTransitScheduleTimeRange *_timeRange;
    struct {
        unsigned int additionalTimeLimit:1;
        unsigned int numAdditionalDepartures:1;
    } _has;
}

@property(nonatomic) double additionalTimeLimit; // @synthesize additionalTimeLimit=_additionalTimeLimit;
@property(nonatomic) unsigned int numAdditionalDepartures; // @synthesize numAdditionalDepartures=_numAdditionalDepartures;
@property(retain, nonatomic) GEOTraitsTransitScheduleTimeRange *timeRange; // @synthesize timeRange=_timeRange;
- (void)mergeFrom:(id)arg1;
- (unsigned long long)hash;
- (_Bool)isEqual:(id)arg1;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (void)copyTo:(id)arg1;
- (void)writeTo:(id)arg1;
- (_Bool)readFrom:(id)arg1;
- (id)dictionaryRepresentation;
- (id)description;
@property(nonatomic) _Bool hasAdditionalTimeLimit;
@property(nonatomic) _Bool hasNumAdditionalDepartures;
@property(readonly, nonatomic) _Bool hasTimeRange;
- (void)dealloc;
- (void)configureWithDefaultStartTime:(double)arg1 duration:(double)arg2 numAdditionalDepartures:(unsigned int)arg3;

@end

