//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSNumber;
@protocol OS_dispatch_queue;

@interface RadioAvailabilityController : NSObject
{
    NSObject<OS_dispatch_queue> *_accessQueue;
    _Bool _hasSuccessfullyLoadedURLBag;
    NSNumber *_lastActiveAccountUniqueIdentifier;
    _Bool _radioAvailable;
}

- (void).cxx_destruct;
- (id)_userDefaultsDomain;
- (void)_reloadRadioAvailabilityWithCompletionHandler:(CDUnknownBlockType)arg1;
- (id)_currentStoreFrontIdentifier;
- (void)_storeFrontDidChangeNotification:(id)arg1;
- (void)_networkReachabilityFlagsDidChangeNotification:(id)arg1;
- (void)getRadioAvailabilityWithCompletionHandler:(CDUnknownBlockType)arg1;
@property(readonly, nonatomic, getter=isRadioAvailable) _Bool radioAvailable;
- (void)dealloc;
- (id)init;

@end

