//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

@class VCVideoStreamReceiver;

@protocol VCVideoStreamReceiverDelegate
- (_Bool)vcVideoStreamReceiver:(VCVideoStreamReceiver *)arg1 didReceiveRemoteFrame:(struct __CVBuffer *)arg2 atTime:(CDStruct_198678f7)arg3;
@end

