//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <QuickLook/QLThumbnailOperation.h>

__attribute__((visibility("hidden")))
@interface QLPDFThumbnailOperation : QLThumbnailOperation
{
    struct CGPDFDocument *_documentRef;
}

- (void)main;
- (void)dealloc;
- (id)initWithPDFDocumentRef:(struct CGPDFDocument *)arg1;

@end

