//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <TVKit/NSObject-Protocol.h>

@class NSString, TVKeyboardContextMenuView;

@protocol TVKeyboardContextMenuViewDelegate <NSObject>
- (void)contextMenuDidFinish:(TVKeyboardContextMenuView *)arg1;

@optional
- (void)contextMenuDidSelectBackspace:(TVKeyboardContextMenuView *)arg1;
- (void)contextMenu:(TVKeyboardContextMenuView *)arg1 didSelectText:(NSString *)arg2;
@end

