//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIViewController.h>

#import <TVKit/UIGestureRecognizerDelegate-Protocol.h>

@class NSArray, NSString, TVFocusRedirectView, TVSegmentedControl, UITapGestureRecognizer;
@protocol TVMenuBarViewControllerDelegate;

@interface TVMenuBarViewController : UIViewController <UIGestureRecognizerDelegate>
{
    TVSegmentedControl *_segmentedControl;
    long long _displayedIndex;
    _Bool _childViewControllerShouldFocus;
    TVFocusRedirectView *_containingView;
    _Bool _firstSelect;
    long long _initialIndex;
    UITapGestureRecognizer *_menuRecognizer;
    id <TVMenuBarViewControllerDelegate> _delegate;
    NSArray *_viewControllers;
    NSArray *_itemIdentifiers;
    NSArray *_itemTitles;
    UIViewController *_childViewController;
}

@property(retain, nonatomic) UIViewController *childViewController; // @synthesize childViewController=_childViewController;
@property(copy, nonatomic) NSArray *itemTitles; // @synthesize itemTitles=_itemTitles;
@property(copy, nonatomic) NSArray *itemIdentifiers; // @synthesize itemIdentifiers=_itemIdentifiers;
@property(copy, nonatomic) NSArray *viewControllers; // @synthesize viewControllers=_viewControllers;
@property(nonatomic) __weak id <TVMenuBarViewControllerDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)_collectionViewDidScrollNotification:(id)arg1;
- (_Bool)gestureRecognizerShouldBegin:(id)arg1;
- (id)_viewsWithDisabledInteractionGivenTransitionContext:(id)arg1;
- (void)didSetChildViewController:(id)arg1 atIndex:(long long)arg2;
- (void)willSetChildViewController:(id)arg1 atIndex:(long long)arg2;
- (void)_setChildViewController:(id)arg1 atSelectedIndex:(long long)arg2 animated:(_Bool)arg3;
- (void)_setChildViewController:(id)arg1 atSelectedIndex:(long long)arg2;
@property(readonly, nonatomic) _Bool fadeThroughContent;
- (void)removeViewControllerAtIndex:(long long)arg1;
- (void)insertViewController:(id)arg1 atIndex:(long long)arg2;
@property(nonatomic) long long selectedIndex;
- (void)_moveFocusToChildViewController;
- (void)_moveFocusToSegmentedControl;
- (_Bool)_segmentedControlContainsFocus;
- (void)_updateChildViewControllerForSelectedIndexAnimated:(_Bool)arg1;
- (void)_updateChildViewControllerForSelectedIndex;
- (void)_setupSegmentedControl;
- (void)_selectedIndexDidChangeAction:(id)arg1;
- (void)_selectAction:(id)arg1;
- (void)_menuButtonAction:(id)arg1;
- (void)viewWillLayoutSubviews;
- (void)loadView;
- (void)focusedViewDidChange;
- (id)preferredFocusedItem;
- (void)dealloc;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

