//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIGestureRecognizer.h>

@class UISwipeGestureRecognizer;

@interface TVPermissiveSwipeGesture : UIGestureRecognizer
{
    struct CGPoint _currentTouchLocation;
    _Bool _swipeGestureIsActive;
    _Bool _swipeGestureRecognizedOrFailed;
    UISwipeGestureRecognizer *_swipeGestureRecognizer;
}

- (void).cxx_destruct;
- (void)_scheduleTouchRestTimeout;
- (void)_fireTouchRestTimeout;
- (void)_cancelTouchRestTimeout;
@property(nonatomic) unsigned long long direction;
- (void)_swipeGestureRecongizerAction:(id)arg1;
- (void)touchesCancelled:(id)arg1 withEvent:(id)arg2;
- (void)touchesEnded:(id)arg1 withEvent:(id)arg2;
- (void)touchesMoved:(id)arg1 withEvent:(id)arg2;
- (void)touchesBegan:(id)arg1 withEvent:(id)arg2;
- (id)initWithTarget:(id)arg1 action:(SEL)arg2;

@end

