//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class NSAttributedString, TVImageView, TVSImageProxy, UIImage, UILabel;

@interface TVReviewCardView : UIView
{
    _Bool _collapsesBadgeSpacing;
    TVSImageProxy *_glyphImageProxy;
    NSAttributedString *_descriptionText;
    UIView *_contentView;
    double _contentInset;
    UILabel *_titleLabel;
    UILabel *_footerLabel;
    UILabel *_descriptionLabel;
    TVImageView *_glyphImageView;
    UIView *_overlayView;
}

@property(retain, nonatomic) UIView *overlayView; // @synthesize overlayView=_overlayView;
@property(retain, nonatomic) TVImageView *glyphImageView; // @synthesize glyphImageView=_glyphImageView;
@property(retain, nonatomic) UILabel *descriptionLabel; // @synthesize descriptionLabel=_descriptionLabel;
@property(retain, nonatomic) UILabel *footerLabel; // @synthesize footerLabel=_footerLabel;
@property(retain, nonatomic) UILabel *titleLabel; // @synthesize titleLabel=_titleLabel;
@property(nonatomic) double contentInset; // @synthesize contentInset=_contentInset;
@property(nonatomic) _Bool collapsesBadgeSpacing; // @synthesize collapsesBadgeSpacing=_collapsesBadgeSpacing;
@property(retain, nonatomic) UIView *contentView; // @synthesize contentView=_contentView;
@property(retain, nonatomic) NSAttributedString *descriptionText; // @synthesize descriptionText=_descriptionText;
@property(retain, nonatomic) TVSImageProxy *glyphImageProxy; // @synthesize glyphImageProxy=_glyphImageProxy;
- (void).cxx_destruct;
- (void)setSelected:(_Bool)arg1 animated:(_Bool)arg2;
@property(retain, nonatomic) UIImage *glyphImage;
- (void)setBackgroundColor:(id)arg1;
@property(retain, nonatomic) NSAttributedString *footer;
- (void)_clearContentViewIfNeeded;
@property(retain, nonatomic) NSAttributedString *title;
- (void)layoutSubviews;
- (id)initWithFrame:(struct CGRect)arg1;

@end

