//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class ACAccountStore, NSArray, NSMutableArray;

@interface CalAccountsProvider : NSObject
{
    _Bool _runningUnitTests;
    NSMutableArray *_accountsWhenRunningUnitTests;
    ACAccountStore *_accountStore;
}

+ (id)_uniqueStringsForUsername:(id)arg1;
+ (id)_existingAccountForAccount:(id)arg1 inStore:(id)arg2;
+ (id)_accountTypeWithIdentifier:(id)arg1 inStore:(id)arg2;
+ (id)_accountsWithAccountType:(id)arg1 inStore:(id)arg2 error:(id *)arg3;
+ (id)verboseDescriptionForAccount:(id)arg1;
+ (id)uniqueStringsForPrincipalPath:(id)arg1;
+ (id)uniqueStringsForHostname:(id)arg1;
+ (id)calDAVChildForParentAccount:(id)arg1;
+ (_Bool)accountIsDuplicate:(id)arg1 inStore:(id)arg2;
+ (id)defaultProvider;
@property(retain, nonatomic) ACAccountStore *accountStore; // @synthesize accountStore=_accountStore;
@property(nonatomic) _Bool runningUnitTests; // @synthesize runningUnitTests=_runningUnitTests;
@property(retain, nonatomic) NSMutableArray *accountsWhenRunningUnitTests; // @synthesize accountsWhenRunningUnitTests=_accountsWhenRunningUnitTests;
- (void).cxx_destruct;
- (id)_supportedDataclassesForMainBundleID;
- (id)_supportedDataclassesForBundleID:(id)arg1;
- (id)_providerForCalDAVAccount:(id)arg1;
- (id)_cachedAccountWithIdentifier:(id)arg1;
- (id)_accountWithIdentifier:(id)arg1;
- (_Bool)saveAccount:(id)arg1 withError:(id *)arg2;
- (_Bool)saveAccount:(id)arg1 verify:(_Bool)arg2 withError:(id *)arg3;
- (void)saveAccount:(id)arg1 withCompletionHandler:(CDUnknownBlockType)arg2;
- (void)saveAccount:(id)arg1 verify:(_Bool)arg2 withCompletionHandler:(CDUnknownBlockType)arg3;
- (void)renewCredentialsForAccount:(id)arg1 forceRenewal:(_Bool)arg2 withCompletionHandler:(CDUnknownBlockType)arg3;
- (_Bool)renewCredentialsForAccount:(id)arg1 forceRenewal:(_Bool)arg2;
- (_Bool)renewCredentialsForAccount:(id)arg1;
- (_Bool)removeAccount:(id)arg1 withError:(id *)arg2;
- (void)removeAccount:(id)arg1 withCompletionHandler:(CDUnknownBlockType)arg2;
- (id)oauthTokenForAccount:(id)arg1 tokenType:(id)arg2;
- (void)messageTraceCurrentAccounts;
- (id)existingAccountForAccount:(id)arg1;
- (id)delegatePrincipalUIDsForAccount:(id)arg1;
- (id)clientTokenForAccountWithIdentifier:(id)arg1;
- (id)allAccountsWithError:(id *)arg1;
- (id)accountWithIdentifier:(id)arg1 returnCachedVersion:(_Bool)arg2;
- (id)accountTypeWithIdentifier:(id)arg1;
- (id)accountsWithServerURL:(id)arg1 username:(id)arg2 returnCachedVersions:(_Bool)arg3;
- (id)accountsWithUsername:(id)arg1;
- (id)accountsWithServerURL:(id)arg1;
- (_Bool)accountIsDuplicate:(id)arg1;
- (_Bool)account:(id)arg1 hasServerURL:(id)arg2;
@property(readonly, nonatomic) NSArray *enabledAccounts;
@property(readonly, nonatomic) NSArray *allAccounts;
- (id)init;

@end

