//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <ScriptProcessor/DTXAllowedRPC-Protocol.h>

@class NSDictionary, NSNumber;

@protocol ScriptAgentAuthorizedAPI <DTXAllowedRPC>
- (void)processBundleWithInfo:(NSDictionary *)arg1;
- (void)_hostTaskDidFinishWithInfo:(NSDictionary *)arg1;
- (void)forceExit;
- (NSNumber *)bundleStatus;
- (NSNumber *)scriptStatus;
- (void)takeScreenshot;
- (void)stopCapture;
- (void)resumeCapture;
- (void)pauseCapture;
- (void)startCaptureWithInfo:(NSDictionary *)arg1;
- (void)stopScript;
- (void)resumeScript;
- (void)pauseScript;
- (void)startScriptWithInfo:(NSDictionary *)arg1;
@end

