//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <IMAP/MFIMAPConnection.h>

@interface MFExchangeConnection : MFIMAPConnection
{
}

- (_Bool)_isFetchResponseValid:(id)arg1;
- (id)_fetchArgumentForMessageSkeletonsWithHeaders:(id)arg1;
- (id)_fetchArgumentForMessageUidsAndFlags;

@end

