//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class MFBaseFilterDataConsumer, MFCountingDataConsumer, NSMutableArray;

@interface MFIMAPDownload : NSObject
{
    unsigned int _uid;
    NSMutableArray *_pendingFetchResults;
    MFCountingDataConsumer *_countingConsumer;
    MFBaseFilterDataConsumer *_mainConsumer;
}

@property(readonly, nonatomic) MFBaseFilterDataConsumer *mainConsumer; // @synthesize mainConsumer=_mainConsumer;
- (unsigned long long)lengthOfDataBeforeLineConversion;
- (void)addCommandsToPipeline:(id)arg1 withCache:(id)arg2;
- (void)processResults;
- (void)handleFetchResult:(id)arg1;
- (void)setError:(id)arg1;
- (id)error;
- (id)data;
- (unsigned long long)bytesFetched;
- (_Bool)isComplete;
- (unsigned long long)expectedLength;
- (unsigned int)uid;
- (id)initWithUid:(unsigned int)arg1;
- (void)dealloc;

@end

