//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <IMAP/NSObject-Protocol.h>

@class NSArray, NSString;

@protocol MFIMAPSequenceIdentifierProvider <NSObject>
- (void)setSequenceIdentifier:(NSString *)arg1 forUIDs:(NSArray *)arg2;
- (NSString *)sequenceIdentifierForUIDs:(NSArray *)arg1;
@end

