//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <QuartzCore/CADisplayLink.h>

@interface CADisplayLink (RCAdditions)
+ (id)rc_displayWithFrameInterval:(long long)arg1 handlerBlock:(CDUnknownBlockType)arg2;
+ (id)rc_displayLinkWithWeakTarget:(id)arg1 selector:(SEL)arg2;
@end

