//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <MPUFoundation/MPUEffectView.h>

@class MPUPinningView, UIImageView;

@interface MPUBlurEffectView : MPUEffectView
{
    MPUPinningView *_blurView;
    UIImageView *_blurImageView;
}

@property(retain, nonatomic) UIImageView *blurImageView; // @synthesize blurImageView=_blurImageView;
@property(retain, nonatomic) MPUPinningView *blurView; // @synthesize blurView=_blurView;
- (void).cxx_destruct;
- (void)updateEffect;
- (void)setReferenceView:(id)arg1;
- (void)layoutSubviews;
- (id)initWithFrame:(struct CGRect)arg1;

@end

