//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <TVServices/TVContentItem.h>

@class NSString;

@interface TVSSContentItem : TVContentItem
{
    NSString *_subtitle;
    NSString *_UTSContentType;
    NSString *_URLFormatString;
}

+ (_Bool)supportsSecureCoding;
@property(copy, nonatomic) NSString *URLFormatString; // @synthesize URLFormatString=_URLFormatString;
@property(copy, nonatomic) NSString *UTSContentType; // @synthesize UTSContentType=_UTSContentType;
@property(copy, nonatomic) NSString *subtitle; // @synthesize subtitle=_subtitle;
- (void).cxx_destruct;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;

@end

