//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <AddressBookUI/ABDatePickerPresentationDelegate-Protocol.h>
#import <AddressBookUI/ABTabOrderDelegate-Protocol.h>

@class ABMultiCellContentView, UIView;

@protocol ABMultiCellContentViewUpdateDelegate <ABTabOrderDelegate, ABDatePickerPresentationDelegate>
- (void)multiCellContentViewWillHideDeleteConfirmation:(ABMultiCellContentView *)arg1;
- (void)multiCellContentViewWillShowDeleteConfirmation:(ABMultiCellContentView *)arg1;
- (void)multiCellContentView:(ABMultiCellContentView *)arg1 didResizeAnimated:(_Bool)arg2;
- (void)multiCellContentView:(ABMultiCellContentView *)arg1 willResizeAnimated:(_Bool)arg2;
- (void)multiCellContentViewDidEndEditing:(ABMultiCellContentView *)arg1;
- (void)multiCellContentView:(ABMultiCellContentView *)arg1 entryFieldDidEndEditing:(UIView *)arg2 forKey:(id)arg3;
- (void)multiCellContentView:(ABMultiCellContentView *)arg1 entryField:(UIView *)arg2 didUpdateValue:(id)arg3 forKey:(id)arg4;
- (void)multiCellContentView:(ABMultiCellContentView *)arg1 entryFieldDidBeginEditing:(UIView *)arg2;
- (_Bool)multiCellContentView:(ABMultiCellContentView *)arg1 entryFieldShouldBeginEditing:(UIView *)arg2;
- (void)multiCellContentView:(ABMultiCellContentView *)arg1 touchesCancelledForView:(UIView *)arg2;
- (void)multiCellContentView:(ABMultiCellContentView *)arg1 touchesEndedForView:(UIView *)arg2;
- (void)multiCellContentView:(ABMultiCellContentView *)arg1 touchesBeganForView:(UIView *)arg2;
@end

