//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class NSAttributedString, NSDictionary, NSNumber;

@interface CNContactMatchInfo : NSObject
{
    _Bool _matchedNameProperty;
    NSNumber *_relevanceScore;
    NSDictionary *_matchedProperties;
    NSAttributedString *_excerpt;
}

@property(nonatomic) _Bool matchedNameProperty; // @synthesize matchedNameProperty=_matchedNameProperty;
@property(retain, nonatomic) NSAttributedString *excerpt; // @synthesize excerpt=_excerpt;
@property(copy, nonatomic) NSDictionary *matchedProperties; // @synthesize matchedProperties=_matchedProperties;
@property(copy, nonatomic) NSNumber *relevanceScore; // @synthesize relevanceScore=_relevanceScore;
- (void)dealloc;

@end

