//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class NSString;

@interface DAMailboxFetchSearchResultRequest : NSObject
{
    int _bodyFormat;
    int _maxSize;
    NSString *_longID;
}

@property(nonatomic) int maxSize; // @synthesize maxSize=_maxSize;
@property(nonatomic) int bodyFormat; // @synthesize bodyFormat=_bodyFormat;
@property(copy, nonatomic) NSString *longID; // @synthesize longID=_longID;
- (void).cxx_destruct;
- (id)description;
- (_Bool)isEqual:(id)arg1;
- (unsigned long long)hash;
- (id)initRequestForBodyFormat:(int)arg1 withLongID:(id)arg2 withBodySizeLimit:(int)arg3;

@end

