//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <PassKit/NSObject-Protocol.h>

@class CNContact, CNContactProperty, CNPostalAddressEditorNavigationController;

@protocol CNPostalAddressEditorDelegate <NSObject>
- (void)postalAddressEditor:(CNPostalAddressEditorNavigationController *)arg1 finishedEditingContact:(CNContact *)arg2;
- (void)postalAddressEditorDidCancel:(CNPostalAddressEditorNavigationController *)arg1;

@optional
- (void)postalAddressEditor:(CNPostalAddressEditorNavigationController *)arg1 finishedEditingProperty:(CNContactProperty *)arg2;
@end

