//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class NSNumber, NSString;

@interface PKAuthenticatorEvaluationRequest : NSObject
{
    NSString *_PINTitle;
    NSNumber *_PINLength;
}

@property(copy, nonatomic) NSNumber *PINLength; // @synthesize PINLength=_PINLength;
@property(copy, nonatomic) NSString *PINTitle; // @synthesize PINTitle=_PINTitle;
- (void)dealloc;
- (id)initWithPolicy:(long long)arg1;
- (id)init;

@end

