//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

#import <PassKit/PKPassFaceDelegate-Protocol.h>
#import <PassKit/PKPasscodeLockManagerObserver-Protocol.h>
#import <PassKit/UIGestureRecognizerDelegate-Protocol.h>

@class NSString, PKPass, PKPassBackFaceView, PKPassColorProfile, PKPassFaceView, PKPassFrontFaceView, PKPasscodeLockManager, UITapGestureRecognizer;
@protocol WLCardViewDelegate;

@interface PKPassView : UIView <PKPassFaceDelegate, UIGestureRecognizerDelegate, PKPasscodeLockManagerObserver>
{
    PKPassFrontFaceView *_frontFace;
    PKPassBackFaceView *_backFace;
    PKPassFaceView *_visibleFace;
    PKPassFaceView *_otherFace;
    PKPassColorProfile *_colorProfile;
    UITapGestureRecognizer *_tapRecognizer;
    long long _priorContentMode;
    _Bool _flipping;
    struct CGRect _delayedFlipFrame;
    double _flipOvershoot;
    double _flipLayoutOvershoot;
    id <WLCardViewDelegate> _delegate;
    PKPasscodeLockManager *_passcodeLockManager;
    CDUnknownBlockType _delayedContentModeCanceller;
    _Bool _backFaceIsTall;
    _Bool _isFrontmostPassView;
    PKPass *_pass;
    long long _contentMode;
    unsigned long long _suppressedContent;
}

@property(nonatomic) _Bool isFrontmostPassView; // @synthesize isFrontmostPassView=_isFrontmostPassView;
@property(nonatomic) _Bool backFaceIsTall; // @synthesize backFaceIsTall=_backFaceIsTall;
@property(nonatomic) unsigned long long suppressedContent; // @synthesize suppressedContent=_suppressedContent;
@property(nonatomic) long long contentMode; // @synthesize contentMode=_contentMode;
@property(nonatomic) id <WLCardViewDelegate> delegate; // @synthesize delegate=_delegate;
@property(readonly, retain, nonatomic) PKPass *pass; // @synthesize pass=_pass;
- (void)_resizePassAnimated:(_Bool)arg1 notify:(_Bool)arg2;
- (void)_flipPass:(_Bool)arg1 fromLeft:(_Bool)arg2 notify:(_Bool)arg3;
- (void)aidUpdated:(id)arg1;
- (void)applicationDidEnterBackground:(id)arg1;
- (void)unregisterForEnterBackgroundNotification;
- (void)registerForEnterBackgroundNotification;
- (void)_updateBackFaceSuppressedContent;
- (void)_updateFrontFaceSuppressedContent;
- (_Bool)_visibleFaceShouldClipForCurrentViewMode:(double *)arg1;
- (unsigned long long)_regionsForCurrentModes;
- (long long)_frontFaceBackgroundModeForContentMode;
- (void)_applyContentMode:(_Bool)arg1;
- (void)passFaceBarcodeButtonPressed:(id)arg1;
- (void)passFaceShareButtonPressed:(id)arg1;
- (void)passFaceFlipButtonPressed:(id)arg1;
- (_Bool)passFaceBarcodeButtonEnabled;
- (_Bool)passFaceDeleteButtonEnabled;
- (void)passFaceDeleteButtonPressed:(id)arg1;
- (void)_updateResizeIfNecessary;
- (void)passcodeLockManager:(id)arg1 didReceivePasscodeSet:(_Bool)arg2;
- (void)resizePassAnimated:(_Bool)arg1 notify:(_Bool)arg2;
- (void)flipPass:(_Bool)arg1 fromLeft:(_Bool)arg2 notify:(_Bool)arg3;
- (void)createBackFaceIfNecessary;
- (void)updateValidityDisplay;
- (void)presentDiff:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (void)layoutSubviews;
- (void)setContentMode:(long long)arg1 animated:(_Bool)arg2 withDelay:(double)arg3;
- (void)setContentMode:(long long)arg1 animated:(_Bool)arg2;
- (void)setDimmer:(double)arg1 animated:(_Bool)arg2;
@property(readonly, nonatomic) _Bool frontFaceBodyContentCreated;
@property(readonly, nonatomic) _Bool isForcedFrontFaceResized;
@property(readonly, nonatomic) _Bool isFrontFaceResized;
@property(readonly, nonatomic) _Bool showingFront;
@property(readonly, nonatomic) NSString *uniqueID;
- (id)item;
- (void)prepareForFlip;
- (_Bool)canResize;
- (_Bool)canFlip;
- (id)snapshotViewOfVisibleFaceAfterScreenUpdates:(_Bool)arg1;
- (id)snapshotOfFrontFace;
- (struct CGRect)frameOfVisibleFace;
- (struct CGSize)sizeOfBackFace;
- (struct CGSize)sizeOfFrontFace;
- (struct CGSize)sizeOfFront;
- (struct CGSize)sizeThatFits:(struct CGSize)arg1;
- (void)tapRecognized:(id)arg1;
- (_Bool)gestureRecognizer:(id)arg1 shouldReceiveTouch:(id)arg2;
- (id)hitTest:(struct CGPoint)arg1 withEvent:(id)arg2;
- (void)setFrame:(struct CGRect)arg1;
- (struct CGRect)frame;
- (void)dealloc;
- (id)initWithPass:(id)arg1 content:(long long)arg2;
- (id)initWithPass:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

