//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UITableViewCell.h>

@interface UITableViewCell (PKAppearanceObject)
- (void)pk_applyAppearance:(struct _PKAppearanceSpecifier *)arg1;
- (id)pk_childrenForAppearance;
@end

