//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

__attribute__((visibility("hidden")))
@interface _UIKeyboardUsageTracking : NSObject
{
}

+ (void)keyboardGestureTwoFingerTap:(_Bool)arg1 withTapCount:(int)arg2;
+ (void)showLowercaseKeyplanePreference:(_Bool)arg1;
+ (void)showCharacterPreviewPreference:(_Bool)arg1;
+ (void)selectedPredictiveInputCandidate:(id)arg1 isAutocorrection:(_Bool)arg2;
+ (void)keyboardGestureSelectedPredictiveInputCandidate;
+ (void)keyboardGestureSetPredictionPreference:(_Bool)arg1;
+ (void)inputSwitcherSetPredictionPreference:(_Bool)arg1;
+ (void)predictionViewState:(_Bool)arg1 forInputMode:(id)arg2;
+ (void)keyboardExtensionsOnDevice;
+ (void)keyboardExtensionCrashed;
+ (void)keyboardExtensionPrimaryLanguageChanged;
+ (void)keyboardSetToInputMode:(id)arg1 fromPrevious:(id)arg2;

@end

