//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/_UIForceLevelClassifier.h>

@interface _UIPolynomialForceLevelClassifier : _UIForceLevelClassifier
{
    double _currentForce;
    struct _UIForceLevelInfo _standardLevel;
    struct _UIForceLevelInfo _strongLevel;
}

@property(nonatomic) struct _UIForceLevelInfo strongLevel; // @synthesize strongLevel=_strongLevel;
@property(nonatomic) struct _UIForceLevelInfo standardLevel; // @synthesize standardLevel=_standardLevel;
- (id)description;
- (void)reset;
- (void)observeTouchWithForceValue:(double)arg1 atTimestamp:(double)arg2 withCentroidAtLocation:(struct CGPoint)arg3;
- (long long)currentForceLevel;
- (long long)_forceLevelForValue:(double)arg1;
- (id)init;

@end

