//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class NSString;

__attribute__((visibility("hidden")))
@interface _UIPopoverViewBackgroundComponentView : UIView
{
    NSString *directionSelector;
}

@property(retain, nonatomic) NSString *directionSelector; // @synthesize directionSelector;
- (void).cxx_destruct;
- (id)_generateBackdropMaskViewForFlag:(long long)arg1;
- (_Bool)_shouldAnimatePropertyWithKey:(id)arg1;

@end

