//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/_UITextViewInteractableItem.h>

#import <UIKit/DDDetectionControllerInteractionDelegate-Protocol.h>

@class NSString, NSURL;

__attribute__((visibility("hidden")))
@interface _UITextViewInteractableLink : _UITextViewInteractableItem <DDDetectionControllerInteractionDelegate>
{
    NSURL *_link;
}

+ (id)interactableLinkWithURL:(id)arg1 range:(struct _NSRange)arg2 subRange:(struct _NSRange)arg3;
@property(retain, nonatomic) NSURL *link; // @synthesize link=_link;
- (void).cxx_destruct;
- (void)actionDidFinish:(id)arg1;
- (void)action:(id)arg1 didDismissAlertController:(id)arg2;
- (void)_dataDetectorAction:(id)arg1;
- (void)_linkInteractionCopyLink;
- (void)_linkInteractionOpenURL;
- (_Bool)_linkInteractionPerformDefaultAction;
- (id)dataDetectorActionsForTextView:(id)arg1;
- (id)linkActions;
- (id)defaultAction;
- (id)actions;
- (_Bool)allowInteraction;
- (id)localizedTitle;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

