//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

__attribute__((visibility("hidden")))
@interface UIAlertControllerDescriptor : NSObject
{
    _Bool _hasTitle;
    _Bool _hasMessage;
    _Bool _hasContentViewController;
    long long _numberOfActions;
}

@property long long numberOfActions; // @synthesize numberOfActions=_numberOfActions;
@property _Bool hasContentViewController; // @synthesize hasContentViewController=_hasContentViewController;
@property _Bool hasMessage; // @synthesize hasMessage=_hasMessage;
@property _Bool hasTitle; // @synthesize hasTitle=_hasTitle;
- (_Bool)isEqual:(id)arg1;

@end

