//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class UIShadowView, UITableView, UIView;

__attribute__((visibility("hidden")))
@interface UICompletionTablePrivate : NSObject
{
    id _delegate;
    UITableView *_table;
    UIShadowView *_shadowView;
    UIView *_topStrokeView;
}

- (void).cxx_destruct;

@end

