//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

#import <UIKit/UIKBCacheableView-Protocol.h>

@class CALayer, NSString;

__attribute__((visibility("hidden")))
@interface UIKBThemedView : UIView <UIKBCacheableView>
{
    CALayer *_borders;
    CALayer *_background;
    _Bool _lightKeyboard;
    _Bool _active;
    _Bool _usePersistentCaching;
    _Bool _noBorders;
    int _style;
    struct UIEdgeInsets _cacheInsets;
}

@property(nonatomic) _Bool noBorders; // @synthesize noBorders=_noBorders;
@property(nonatomic) _Bool usePersistentCaching; // @synthesize usePersistentCaching=_usePersistentCaching;
@property(nonatomic) struct UIEdgeInsets cacheInsets; // @synthesize cacheInsets=_cacheInsets;
@property(nonatomic) int style; // @synthesize style=_style;
@property(nonatomic) _Bool active; // @synthesize active=_active;
@property(readonly, nonatomic) _Bool keepNonPersistent;
@property(readonly, nonatomic) double cachedWidth;
@property(readonly, nonatomic) _Bool cacheDeferable;
- (void)drawContentsOfRenderers:(id)arg1;
- (id)traitsForCurrentStyle;
- (id)borderFilterTypeForCurrentStyle;
- (void)displayLayer:(id)arg1;
- (void)_populateLayer:(id)arg1 withContents:(id)arg2;
- (void)layoutSubviews;
- (id)cacheKeysForRenderFlags:(id)arg1;
@property(readonly, nonatomic) NSString *cacheKey;
- (void)_setRenderConfig:(id)arg1;
- (void)didMoveToWindow;
- (_Bool)_canDrawContent;
- (_Bool)_hasInsets;
- (id)initWithFrame:(struct CGRect)arg1 style:(int)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

