//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIKeyboardCandidateView.h>

#import <UIKit/UIKeyboardCandidateViewInline-Protocol.h>

@class NSString;

__attribute__((visibility("hidden")))
@interface UIKeyboardCandidateView_Floating : UIKeyboardCandidateView <UIKeyboardCandidateViewInline>
{
    struct CGRect _collapsedRect;
    struct CGSize presentationSize;
}

+ (double)defaultExtendedControlHeight;
@property struct CGSize presentationSize; // @synthesize presentationSize;
- (id)_inheritedRenderConfig;
- (void)candidatesDidChange;
- (id)activeCandidateList;
- (void)setCandidateViewExtended:(_Bool)arg1;
- (unsigned long long)_numberOfColumns:(_Bool)arg1;
- (void)layoutSubviews;
- (id)initWithFrame:(struct CGRect)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

