//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

#import <UIKit/NSCoding-Protocol.h>
#import <UIKit/NSISVariableDelegate-Protocol.h>
#import <UIKit/_UILayoutItem-Protocol.h>

@class NSArray, NSISVariable, NSLayoutDimension, NSLayoutXAxisAnchor, NSLayoutYAxisAnchor, NSString, UIView;

@interface UILayoutGuide : NSObject <_UILayoutItem, NSISVariableDelegate, NSCoding>
{
    struct CGRect _layoutFrame;
    _Bool _isLayoutFrameValid;
    UIView *_unsafeUnretainedOwningView;
    _Bool _allowOwningViewSetting;
    _Bool _isLockedToOwningView;
    _Bool _useManualLayoutFrame;
    _Bool __shouldBeArchived;
    UIView *_owningView;
    NSString *_identifier;
    NSISVariable *_minXVariable;
    NSISVariable *_minYVariable;
    NSISVariable *_boundsWidthVariable;
    NSISVariable *_boundsHeightVariable;
    NSArray *_systemConstraints;
    NSLayoutXAxisAnchor *_leadingAnchor;
    NSLayoutXAxisAnchor *_trailingAnchor;
    NSLayoutXAxisAnchor *_leftAnchor;
    NSLayoutXAxisAnchor *_rightAnchor;
    NSLayoutYAxisAnchor *_topAnchor;
    NSLayoutYAxisAnchor *_bottomAnchor;
    NSLayoutDimension *_widthAnchor;
    NSLayoutDimension *_heightAnchor;
    NSLayoutXAxisAnchor *_centerXAnchor;
    NSLayoutYAxisAnchor *_centerYAnchor;
}

+ (double)_defaultSpacingBetweenGuidesForResolvingSymbolicConstant;
@property(nonatomic, setter=_setShouldBeArchived:) _Bool _shouldBeArchived; // @synthesize _shouldBeArchived=__shouldBeArchived;
@property(readonly, nonatomic) _Bool _useManualLayoutFrame; // @synthesize _useManualLayoutFrame;
@property(retain, nonatomic, setter=_setSystemConstraints:) NSArray *_systemConstraints; // @synthesize _systemConstraints;
@property(nonatomic, getter=_isLockedToOwningView, setter=_setLockedToOwningView:) _Bool _lockedToOwningView; // @synthesize _lockedToOwningView=_isLockedToOwningView;
@property(retain, nonatomic, setter=_setBoundsHeightVariable:) NSISVariable *_boundsHeightVariable; // @synthesize _boundsHeightVariable;
@property(retain, nonatomic, setter=_setBoundsWidthVariable:) NSISVariable *_boundsWidthVariable; // @synthesize _boundsWidthVariable;
@property(retain, nonatomic, setter=_setMinYVariable:) NSISVariable *_minYVariable; // @synthesize _minYVariable;
@property(retain, nonatomic, setter=_setMinXVariable:) NSISVariable *_minXVariable; // @synthesize _minXVariable;
@property(copy, nonatomic) NSString *identifier; // @synthesize identifier=_identifier;
@property(nonatomic) __weak UIView *owningView; // @synthesize owningView=_owningView;
@property(nonatomic, setter=_setAllowOwningViewSetting:) _Bool _allowOwningViewSetting; // @synthesize _allowOwningViewSetting;
- (void).cxx_destruct;
@property(readonly) NSLayoutYAxisAnchor *centerYAnchor; // @synthesize centerYAnchor=_centerYAnchor;
@property(readonly) NSLayoutXAxisAnchor *centerXAnchor; // @synthesize centerXAnchor=_centerXAnchor;
@property(readonly) NSLayoutDimension *heightAnchor; // @synthesize heightAnchor=_heightAnchor;
@property(readonly) NSLayoutDimension *widthAnchor; // @synthesize widthAnchor=_widthAnchor;
@property(readonly) NSLayoutYAxisAnchor *bottomAnchor; // @synthesize bottomAnchor=_bottomAnchor;
@property(readonly) NSLayoutYAxisAnchor *topAnchor; // @synthesize topAnchor=_topAnchor;
@property(readonly) NSLayoutXAxisAnchor *rightAnchor; // @synthesize rightAnchor=_rightAnchor;
@property(readonly) NSLayoutXAxisAnchor *leftAnchor; // @synthesize leftAnchor=_leftAnchor;
@property(readonly) NSLayoutXAxisAnchor *trailingAnchor; // @synthesize trailingAnchor=_trailingAnchor;
@property(readonly) NSLayoutXAxisAnchor *leadingAnchor; // @synthesize leadingAnchor=_leadingAnchor;
- (id)_createAnchorWithClass:(Class)arg1 attribute:(long long)arg2;
- (id)methodSignatureForSelector:(SEL)arg1;
- (void)forwardInvocation:(id)arg1;
- (id)nsis_descriptionOfVariable:(id)arg1;
- (void)nsis_valueOfVariable:(id)arg1 didChangeInEngine:(id)arg2;
- (_Bool)nsis_valueOfVariableIsUserObservable:(id)arg1;
- (_Bool)nsis_shouldIntegralizeVariable:(id)arg1;
- (void *)_referenceView;
- (_Bool)nsli_isCollectingConstraintChangesForLaterCoordinatedFlush:(id)arg1;
- (id)nsli_contentHeightVariable;
- (id)nsli_contentWidthVariable;
- (id)nsli_boundsHeightVariable;
- (id)nsli_boundsWidthVariable;
- (id)nsli_minYVariable;
- (id)nsli_minXVariable;
- (_Bool)nsli_lowerAttribute:(int)arg1 intoExpression:(id)arg2 withCoefficient:(double)arg3 container:(id)arg4;
- (_Bool)nsli_lowerAttribute:(int)arg1 intoExpression:(id)arg2 withCoefficient:(double)arg3 forConstraint:(id)arg4;
- (double)nsli_marginOffsetForAttribute:(long long)arg1;
- (id)nsli_installedConstraints;
- (_Bool)nsli_removeConstraint:(id)arg1;
- (void)nsli_addConstraint:(id)arg1;
- (_Bool)nsli_isFlipped;
- (unsigned long long)nsli_autoresizingMask;
- (_Bool)nsli_descriptionIncludesPointer;
- (id)nsli_description;
- (_Bool)nsli_resolvedValue:(double *)arg1 forSymbolicConstant:(id)arg2 inConstraint:(id)arg3 error:(id *)arg4;
- (id)nsli_superitem;
- (struct CGSize)nsli_convertSizeFromEngineSpace:(struct CGSize)arg1;
- (struct CGSize)nsli_convertSizeToEngineSpace:(struct CGSize)arg1;
- (id)nsli_layoutEngine;
- (void)_snipReferencingConstraints;
@property(readonly, copy) NSString *description;
- (void)dealloc;
- (id)initWithCoder:(id)arg1;
- (id)init;
- (void)encodeWithCoder:(id)arg1;
@property(readonly, nonatomic) struct CGRect layoutFrame;
- (void)_setManualLayoutFrame:(struct CGRect)arg1;
- (void)_setOwningView:(id)arg1;
- (void)_owningViewIsDeallocating;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

