//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

#import <UIKit/NSCoding-Protocol.h>
#import <UIKit/_UIMultilineTextContentSizing-Protocol.h>

@class NSAttributedString, NSMutableDictionary, NSString, UIColor, UIFont, _UILabelScaledMetrics;

@interface UILabel : UIView <_UIMultilineTextContentSizing, NSCoding>
{
    struct CGSize _size;
    UIColor *_highlightedColor;
    long long _numberOfLines;
    long long _measuredNumberOfLines;
    double _lastLineBaseline;
    double _previousBaselineOffsetFromBottom;
    double _firstLineBaseline;
    double _previousFirstLineBaseline;
    double _minimumScaleFactor;
    id _content;
    NSAttributedString *_synthesizedAttributedText;
    NSMutableDictionary *_defaultAttributes;
    double _minimumFontSize;
    long long _lineSpacing;
    id _layout;
    _UILabelScaledMetrics *_scaledMetrics;
    struct {
        unsigned int unused1:3;
        unsigned int highlighted:1;
        unsigned int autosizeTextToFit:1;
        unsigned int autotrackTextToFit:1;
        unsigned int baselineAdjustment:2;
        unsigned int enabled:1;
        unsigned int wordRoundingEnabled:1;
        unsigned int explicitAlignment:1;
        unsigned int marqueeEnabled:1;
        unsigned int marqueeRunable:1;
        unsigned int marqueeRequired:1;
        unsigned int drawsLetterpress:1;
        unsigned int unused3:1;
        unsigned int usesExplicitPreferredMaxLayoutWidth:1;
        unsigned int determiningPreferredMaxLayoutWidth:1;
        unsigned int inSecondConstraintsPass:1;
        unsigned int drawsDebugBaselines:1;
        unsigned int explicitBaselineOffset:1;
        unsigned int usesSimpleTextEffects:1;
        unsigned int isComplexString:1;
        unsigned int isVariableLengthString:1;
        unsigned int wantsUnderlineForAccessibilityButtonShapesEnabled:1;
    } _textLabelFlags;
    _Bool __textColorFollowsTintColor;
    double _preferredMaxLayoutWidth;
}

+ (struct CGSize)_legacy_adjustSizeForWebKitConstraining:(struct CGSize)arg1 withFont:(id)arg2;
+ (struct CGRect)_insetRect:(struct CGRect)arg1 forAttributedString:(id)arg2 withDefaultFont:(id)arg3 inView:(id)arg4;
+ (struct UIEdgeInsets)_insetsForAttributedString:(id)arg1 withDefaultFont:(id)arg2 inView:(id)arg3;
+ (struct UIEdgeInsets)_insetsForString:(id)arg1 withFont:(id)arg2 inView:(id)arg3;
+ (struct __CFCharacterSet *)_tooBigChars;
+ (id)_defaultAttributes;
+ (id)defaultFont;
+ (Class)layerClass;
@property(nonatomic, setter=_setTextColorFollowsTintColor:) _Bool _textColorFollowsTintColor; // @synthesize _textColorFollowsTintColor=__textColorFollowsTintColor;
@property(nonatomic) double minimumScaleFactor; // @synthesize minimumScaleFactor=_minimumScaleFactor;
@property(retain, nonatomic) UIColor *highlightedTextColor; // @synthesize highlightedTextColor=_highlightedColor;
@property(nonatomic) double preferredMaxLayoutWidth; // @synthesize preferredMaxLayoutWidth=_preferredMaxLayoutWidth;
- (void).cxx_destruct;
- (_Bool)_usesSimpleTextEffects;
- (void)_setUsesSimpleTextEffects:(_Bool)arg1;
- (_Bool)drawsUnderline;
- (void)setDrawsUnderline:(_Bool)arg1;
- (id)letterpressStyle;
- (void)setLetterpressStyle:(id)arg1;
- (_Bool)drawsLetterpress;
- (void)setDrawsLetterpress:(_Bool)arg1;
- (void)setMarqueeRunning:(_Bool)arg1;
- (_Bool)marqueeEnabled;
- (_Bool)marqueeRunning;
- (void)_stopMarqueeWithRedisplay:(_Bool)arg1;
- (void)_startMarqueeIfNecessary;
- (void)_startMarquee;
- (void)_drawFullMarqueeTextInRect:(struct CGRect)arg1;
- (void)_coordinateBeginTimeForMarqueeAnimations:(double)arg1;
- (double)_maximumMarqueeTextWidth;
- (id)_siblingMarqueeLabels;
- (void)setMarqueeEnabled:(_Bool)arg1;
- (_Bool)_shouldDrawUnderlinesLikeWebKit;
- (void)_setWordRoundingEnabled:(_Bool)arg1;
- (void)drawRect:(struct CGRect)arg1;
- (void)_drawTextInRect:(struct CGRect)arg1 baselineCalculationOnly:(_Bool)arg2;
- (_Bool)_updateScaledMetricsForRect:(struct CGRect)arg1;
- (_Bool)_drawsUnderline;
- (void)drawTextInRect:(struct CGRect)arg1;
- (struct CGSize)sizeThatFits:(struct CGSize)arg1;
- (struct CGSize)intrinsicContentSize;
- (struct CGSize)_intrinsicSizeWithinSize:(struct CGSize)arg1;
- (void)traitCollectionDidChange:(id)arg1;
- (void)updateConstraints;
- (void)_resetToBeginningOfDoublePass;
- (void)_setInSecondConstraintsPass:(_Bool)arg1;
- (void)_prepareForSecondIntrinsicContentSizeCalculationWithLayoutEngineBounds:(struct CGRect)arg1;
- (void)_prepareForFirstIntrinsicContentSizeCalculation;
- (void)invalidateIntrinsicContentSize;
- (_Bool)_needsDoubleUpdateConstraintsPass;
- (double)_firstBaselineOffsetFromTop;
- (double)_baselineOffsetFromBottom;
- (struct CGRect)_ensureBaselineMetricsReturningBounds;
@property(readonly, nonatomic) double _lastLineBaseline;
@property(nonatomic) long long baselineAdjustment;
- (id)_layoutDebuggingTitle;
@property(nonatomic, setter=_setDrawsDebugBaselines:) _Bool _drawsDebugBaselines;
@property(nonatomic) _Bool adjustsLetterSpacingToFitWidth;
@property(nonatomic) long long lineSpacing;
@property(nonatomic) long long numberOfLines;
@property(nonatomic) long long lineBreakMode;
- (void)_setLineBreakMode:(long long)arg1;
@property(nonatomic, getter=isHighlighted) _Bool highlighted;
- (double)shadowBlur;
- (void)setShadowBlur:(double)arg1;
@property(nonatomic) struct CGSize shadowOffset;
- (void)_setShadowUIOffset:(struct UIOffset)arg1;
@property(retain, nonatomic) UIColor *shadowColor;
- (id)_shadow;
- (void)_setShadow:(id)arg1;
@property(retain, nonatomic) UIFont *font;
- (void)_setFont:(id)arg1;
- (void)_baselineOffsetParametersDidChange;
- (id)currentTextColor;
- (id)_disabledFontColor;
- (void)setSemanticContentAttribute:(long long)arg1;
@property(nonatomic) long long textAlignment;
- (void)_setTextAlignment:(long long)arg1;
- (void)tintColorDidChange;
@property(nonatomic) _Bool allowsDefaultTighteningForTruncation;
- (void)_setAllowsDefaultTighteningForTruncation:(_Bool)arg1;
@property(nonatomic) double minimumFontSize;
- (double)_minimumFontSize;
- (void)_setMinimumFontSize:(double)arg1;
- (id)_associatedScalingLabel;
- (double)_actualScaleFactor;
@property(nonatomic) _Bool adjustsFontSizeToFitWidth;
@property(retain, nonatomic) UIColor *textColor;
- (void)_setTextColor:(id)arg1;
@property(nonatomic, getter=isEnabled) _Bool enabled;
@property(nonatomic, getter=isUserInteractionEnabled) _Bool userInteractionEnabled; // @dynamic userInteractionEnabled;
@property(copy, nonatomic) NSAttributedString *attributedText;
- (void)_setAttributedText:(id)arg1 andTakeOwnership:(_Bool)arg2;
@property(copy, nonatomic) NSString *text;
- (void)_setText:(id)arg1;
- (struct UIEdgeInsets)_contentInsetsFromFonts;
- (void)_invalidateTextSize;
- (struct CGRect)_textRectForBounds:(struct CGRect)arg1 limitedToNumberOfLines:(long long)arg2 includingShadow:(_Bool)arg3;
- (_Bool)_shouldCeilSizeToViewScale;
- (id)_stringDrawingContext;
- (struct CGRect)textRectForBounds:(struct CGRect)arg1 limitedToNumberOfLines:(long long)arg2;
- (struct CGSize)textSize;
- (void)dealloc;
- (void)encodeWithCoder:(id)arg1;
- (_Bool)_attributedStringHasAttributesNotCoveredByPrimitives;
- (id)initWithCoder:(id)arg1;
- (void)setBounds:(struct CGRect)arg1;
- (void)setFrame:(struct CGRect)arg1;
- (void)_invalidateAsNeededForNewSize:(struct CGSize)arg1 oldSize:(struct CGSize)arg2 withLinkCheck:(_Bool)arg3;
- (void)_didMoveFromWindow:(id)arg1 toWindow:(id)arg2;
- (void)_updateVariableLengthString;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)_commonInit;
@property(retain, nonatomic, getter=_synthesizedAttributedText, setter=_setSynthesizedAttributedText:) NSAttributedString *_synthesizedAttributedText;
- (void)_invalidateSynthesizedAttributedTextAndLayout;
- (void)_invalidateLayout;
- (void)_invalidateDefaultAttributes;
- (id)_synthesizedTextAttributes;
- (id)_compatibilityAttributedString;
- (void)_setDefaultAttributes:(id)arg1;
- (id)_defaultAttributes;
- (double)_preferredMaxLayoutWidth;
- (id)_scriptingInfo;
@property(nonatomic, setter=_setLastLineBaselineFrameOriginY:) double _lastLineBaselineFrameOriginY;
@property(nonatomic, setter=_setFirstLineBaselineFrameOriginY:) double _firstLineBaselineFrameOriginY;
@property(nonatomic, setter=_setFirstLineCapFrameOriginY:) double _firstLineCapFrameOriginY;
@property(readonly, nonatomic) double _firstLineBaselineOffsetFromBoundsTop;
@property(readonly, nonatomic) double _capOffsetFromBoundsTop;
- (long long)_measuredNumberOfLines;
@property(nonatomic, setter=_setWantsUnderlineForAccessibilityButtonShapesEnabled:) _Bool _wantsUnderlineForAccessibilityButtonShapesEnabled; // @dynamic _wantsUnderlineForAccessibilityButtonShapesEnabled;
- (void)_didChangeFromIdiom:(long long)arg1 onScreen:(id)arg2 traverseHierarchy:(_Bool)arg3;
- (_Bool)_shouldShowAccessibilityButtonShapesUnderline;
- (void)_accessibilityButtonShapesChangedNotification:(id)arg1;
- (void)_accessibilityButtonShapesParametersDidChange;
- (void)_resetUsesExplicitPreferredMaxLayoutWidth;
- (struct CGSize)rawSize;
- (void)setRawSize:(struct CGSize)arg1;
- (void)drawContentsInRect:(struct CGRect)arg1;
- (struct CGRect)textRectForBounds:(struct CGRect)arg1;
- (struct CGSize)textSizeForWidth:(double)arg1;
- (_Bool)centersHorizontally;
- (void)setCentersHorizontally:(_Bool)arg1;
- (id)color;
- (void)setColor:(id)arg1;
- (void)_setColor:(id)arg1;
- (_Bool)autotrackTextToFit;
- (void)setAutotrackTextToFit:(_Bool)arg1;
- (unsigned long long)defaultAccessibilityTraits;
- (_Bool)isElementAccessibilityExposedToInterfaceBuilder;
- (_Bool)isAccessibilityElementByDefault;
- (id)_image;
- (_Bool)_isTextFieldCenteredLabel;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

