//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class UIViewController;

__attribute__((visibility("hidden")))
@interface UIStoryboardScene : NSObject
{
    UIViewController *sceneViewController;
}

@property(retain, nonatomic) UIViewController *sceneViewController; // @synthesize sceneViewController;
- (void)dealloc;

@end

