//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

#import <UIKit/NSCopying-Protocol.h>
#import <UIKit/NSSecureCoding-Protocol.h>

@class NSDictionary;

@interface UITraitCollection : NSObject <NSCopying, NSSecureCoding>
{
    CDStruct_a687ed74 _builtinTraits;
    NSDictionary *_clientDefinedTraits;
}

+ (id)_emptyTraitCollection;
+ (id)_traitCollectionWithValue:(id)arg1 forTraitNamed:(id)arg2;
+ (id)traitCollectionWithForceTouchCapability:(long long)arg1;
+ (id)traitCollectionWithUserInterfaceStyle:(long long)arg1;
+ (id)traitCollectionWithVerticalSizeClass:(long long)arg1;
+ (id)traitCollectionWithHorizontalSizeClass:(long long)arg1;
+ (id)traitCollectionWithDisplayScale:(double)arg1;
+ (id)traitCollectionWithInteractionModel:(unsigned long long)arg1;
+ (id)traitCollectionWithTouchLevel:(long long)arg1;
+ (id)traitCollectionWithUserInterfaceIdiom:(long long)arg1;
+ (id)traitCollectionWithTraitsFromCollections:(id)arg1;
+ (_Bool)supportsSecureCoding;
+ (id)traitCollectionWithBarPosition:(long long)arg1;
+ (id)traitCollectionWithBarMetrics:(long long)arg1;
@property(readonly, nonatomic) long long forceTouchCapability;
- (long long)userInterfaceStyle;
@property(readonly, nonatomic) long long verticalSizeClass;
@property(readonly, nonatomic) long long horizontalSizeClass;
@property(readonly, nonatomic) double displayScale;
- (unsigned long long)interactionModel;
- (long long)touchLevel;
@property(readonly, nonatomic) long long userInterfaceIdiom;
- (id)_valueForTraitNamed:(id)arg1;
- (_Bool)_matchesIntersectionWithTraitCollection:(id)arg1;
- (_Bool)containsTraitsInCollection:(id)arg1;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)initWithCoder:(id)arg1;
- (void)encodeWithCoder:(id)arg1;
- (id)description;
- (long long)_compare:(id)arg1;
- (_Bool)isEqual:(id)arg1;
- (unsigned long long)hash;
- (void)dealloc;
- (id)init;
- (id)_initWithBuiltinTraitStorage:(CDStruct_a687ed74 *)arg1 clientDefinedTraits:(id)arg2;
- (id)_namedImageDescription;
@property(readonly, nonatomic) long long barPosition;
@property(readonly, nonatomic) long long barMetrics;

@end

