//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class CADisplayLink, UIView;

__attribute__((visibility("hidden")))
@interface UIViewHeartbeat : NSObject
{
    UIView *_view;
    SEL _selector;
    CADisplayLink *_heartbeat;
}

+ (void)stopHeartbeatWithView:(id)arg1 selector:(SEL)arg2;
+ (void)startHeartbeatWithView:(id)arg1 selector:(SEL)arg2 inRunLoopMode:(id)arg3;
- (void).cxx_destruct;
- (void)_updateDisplayLink:(id)arg1;
- (void)dealloc;

@end

