//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import <IBAppleTVCocoaTouchImageCatalogToolExtensions/IBICSchemaProvider-Protocol.h>

@class IBICDeviceOrientation, IBICExtent, IBICFileType, IBICIdiom, IBICLocus, IBICPlatform, IBICScale, IBICSize, IBICSystemVersion, NSString;

@interface IBICAppleTVSchemaAdditions : NSObject <IBICSchemaProvider>
{
    IBICPlatform *_tvPlatform;
    IBICIdiom *_universalIdiom;
    IBICIdiom *_tvIdiom;
    IBICIdiom *_marketingIdiom;
    IBICScale *_720Scale;
    IBICScale *_oneXScale;
    IBICSize *_size360x216Deprecated;
    IBICSize *_size370x222Deprecated;
    IBICSize *_size400x240;
    IBICSize *_size1280x768;
    IBICSize *_size1920x720;
    IBICSystemVersion *_tvosV9;
    IBICFileType *_pngFileType;
    IBICFileType *_jpegFileType;
    IBICFileType *_pdfFileType;
    IBICExtent *_extentFullScreen;
    IBICDeviceOrientation *_landscapeOrientation;
    IBICLocus *_primaryAppIcon;
    IBICLocus *_topShelfImage;
}

+ (_Bool)supportsRemoteToolsTargetingPlatformNamed:(id)arg1;
- (void).cxx_destruct;
- (void)registerBrandAssetCollectionSlots:(id)arg1;
- (void)registerDataSetSlots:(id)arg1;
- (void)registerLaunchImageSetSlots:(id)arg1;
- (void)registerImageSetSlots:(id)arg1;
- (void)registerSlotComponents:(id)arg1;
- (void)captureExistingComponents:(id)arg1;
- (double)precedence;
- (void)registerSchemaComponents:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

