//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class NSMutableDictionary;

@interface CNCache : NSObject
{
    NSMutableDictionary *_cache;
}

- (id)allKeys;
- (void)setObject:(id)arg1 forKeyedSubscript:(id)arg2;
- (void)setObject:(id)arg1 forKey:(id)arg2;
- (id)objectForKeyedSubscript:(id)arg1;
- (id)objectForKey:(id)arg1 onCacheMiss:(CDUnknownBlockType)arg2;
- (id)objectForKey:(id)arg1;
- (void)dealloc;
- (id)init;

@end

