//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSUserDefaults.h>

@class NSMutableDictionary;
@protocol UIFoundationGlobalUserDefaultsHelper;

@interface _UIGlobalUserDefaults : NSUserDefaults
{
    id <UIFoundationGlobalUserDefaultsHelper> _userDefaultsHelper;
    NSMutableDictionary *_userDefaultsDictionary;
    unsigned long long _backgroundTaskIdentifier;
}

@property(nonatomic) unsigned long long backgroundTaskIdentifier; // @synthesize backgroundTaskIdentifier=_backgroundTaskIdentifier;
@property(retain, nonatomic) NSMutableDictionary *userDefaultsDictionary; // @synthesize userDefaultsDictionary=_userDefaultsDictionary;
@property(retain, nonatomic) id <UIFoundationGlobalUserDefaultsHelper> userDefaultsHelper; // @synthesize userDefaultsHelper=_userDefaultsHelper;
- (void)_synchronizeIfNeeded;
- (void)_scheduleSynchronization;
- (id)_userDefaultsHelperCreateIfNeeded;
- (void)loadDefaultsDictionary;
- (void)loadDefaultsDictionaryIfNeeded;
- (_Bool)synchronize;
- (void)removeObjectForKey:(id)arg1;
- (void)setObject:(id)arg1 forKey:(id)arg2;
- (id)objectForKey:(id)arg1;
- (void)dealloc;
- (id)init;

@end

