//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import <WebUI/WBUFormMetadataObserver-Protocol.h>

@class NSMutableDictionary, NSString, NSTimer, UIView, WBUFormAutoFillWebView, WBUFormAutocompleteStateWK2, _WKRemoteObjectInterface;
@protocol WBUFormAutoFillControllerDelegate, WBUFormAutoFillWebView, WBUFormAutoFiller;

@interface WBUFormAutoFillController : NSObject <WBUFormMetadataObserver>
{
    WBUFormAutoFillWebView *_webView;
    id <WBUFormAutoFillControllerDelegate> _delegate;
    _WKRemoteObjectInterface *_remoteObjectInterface;
    id <WBUFormAutoFiller> _autoFiller;
    NSMutableDictionary *_metadataReplyIdentifierToCompletion;
    WBUFormAutocompleteStateWK2 *_state;
    NSTimer *_prefillTimer;
}

- (void).cxx_destruct;
- (void)willNavigateFrame:(id)arg1 withUnsubmittedForm:(id)arg2 loadingIsDeferred:(_Bool)arg3;
- (void)didFillGeneratedPasswordInForm:(id)arg1 inFrame:(id)arg2;
- (void)textDidChangeInTextField:(id)arg1 inForm:(id)arg2 inFrame:(id)arg3;
- (void)didCollectFormMetadata:(id)arg1 textFieldMetadata:(id)arg2 replyIdentifier:(id)arg3;
- (void)didCollectFormMetadataForPreFilling:(id)arg1 atURL:(id)arg2 ancestorFramesOfFormToPreFill:(id)arg3;
- (void)didCollectURLsForPreFilling:(id)arg1 atURL:(id)arg2;
- (void)willSubmitFormValues:(id)arg1 userObject:(id)arg2 submissionHandler:(CDUnknownBlockType)arg3;
- (void)fieldFocusedWithInputSession:(id)arg1;
@property(readonly, nonatomic) UIView<WBUFormAutoFillWebView> *webView;
- (void)_autoFillLoginFormSynchronously:(id)arg1 inFrame:(id)arg2;
- (void)willSubmitForm:(id)arg1 inFrame:(id)arg2 submissionHandler:(CDUnknownBlockType)arg3;
- (void)setFormControls:(id)arg1 areAutoFilled:(_Bool)arg2 andClearField:(id)arg3 inFrame:(id)arg4;
- (void)fillTextField:(id)arg1 inFrame:(id)arg2 withGeneratedPassword:(id)arg3;
- (void)annotateForm:(id)arg1 inFrame:(id)arg2 withValues:(id)arg3;
- (void)autoFillForm:(id)arg1 inFrame:(id)arg2 withGeneratedPassword:(id)arg3;
- (void)autoFillFormInFrame:(id)arg1 withValues:(id)arg2 setAutoFilled:(_Bool)arg3 andFocusField:(id)arg4;
- (void)fetchMetadataForTextField:(id)arg1 inFrame:(id)arg2 withCompletion:(CDUnknownBlockType)arg3;
- (void)textFieldFocused:(id)arg1 inForm:(id)arg2 inFrame:(id)arg3 inputSession:(id)arg4;
- (void)passwordFieldFocused:(id)arg1 inForm:(id)arg2 inFrame:(id)arg3 inputSession:(id)arg4;
- (void)usernameFieldFocused:(id)arg1 inForm:(id)arg2 inFrame:(id)arg3 inputSession:(id)arg4;
- (void)_fieldFocused:(id)arg1 inForm:(id)arg2 inFrame:(id)arg3 inputSession:(id)arg4;
- (void)autoFill;
- (void)prefillFormsSoonIfNeeded;
- (void)_prefillTimerFired:(id)arg1;
- (void)invalidate;
- (void)dealloc;
- (id)initWithWebView:(id)arg1 delegate:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

