//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <CloudKit/CKOperation.h>

@interface CKModifyBadgeOperation : CKOperation
{
    unsigned long long _badgeValue;
    CDUnknownBlockType _modifyBadgeCompletionBlock;
}

@property(copy, nonatomic) CDUnknownBlockType modifyBadgeCompletionBlock; // @synthesize modifyBadgeCompletionBlock=_modifyBadgeCompletionBlock;
@property(nonatomic) unsigned long long badgeValue; // @synthesize badgeValue=_badgeValue;
- (void).cxx_destruct;
- (unsigned long long)activityStart;
- (void)_finishOnCallbackQueueWithError:(id)arg1;
- (void)fillOutOperationInfo:(id)arg1;
- (void)performCKOperation;
- (id)initWithBadgeValue:(unsigned long long)arg1;
- (id)init;

@end

