//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSError.h>

@interface NSError (CKUtilsAdditions)
+ (id)errorFromErrno;
+ (id)errorWithPOSIXCode:(int)arg1;
- (_Bool)isPOSIXErrorCode:(long long)arg1;
@end

