//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <CellularPlanManager/NSObject-Protocol.h>

@class CTCellularPlanItem, NSData, NSDictionary, NSNumber, NSString;

@protocol CTCellularPlanClient <NSObject>
- (void)setActivePlan:(NSData *)arg1 completion:(void (^)(_Bool, NSError *))arg2;
- (void)updatePlansDatabase;
- (void)expirePlan;
- (void)launchSequoia;
- (void)setLatitude:(NSNumber *)arg1 andLongitude:(NSNumber *)arg2;
- (void)latitudeLongitudeOverride:(void (^)(double, double))arg1;
- (void)setMcc:(long long)arg1 andMnc:(long long)arg2;
- (void)mccMncOverride:(void (^)(long long, long long))arg1;
- (void)setSelectedProxy:(long long)arg1;
- (void)getSelectedProxy:(void (^)(long long))arg1;
- (void)setSelectedEnv:(long long)arg1;
- (void)getSelectedEnv:(void (^)(long long))arg1;
- (void)setIMEIPrefix:(NSString *)arg1;
- (void)getIMEIPrefix:(void (^)(NSString *))arg1;
- (void)getCurrentPlanType:(void (^)(long long))arg1;
- (void)openInternalUrlId:(long long)arg1;
- (void)getDeviceInfo:(void (^)(NSDictionary *))arg1;
- (void)retrieveRequestSettings:(void (^)(NSDictionary *, NSDictionary *, NSDictionary *))arg1;
- (void)fetchNewProfilesWithCompletion:(void (^)(_Bool, NSError *))arg1 additionalParameters:(NSDictionary *)arg2;
- (void)registerHasNewProfileCompletion:(void (^)(_Bool))arg1;
- (void)setUserInPurchaseFlow:(_Bool)arg1;
- (void)didPurchasePlanWithIccid:(NSString *)arg1 downloadProfile:(_Bool)arg2;
- (void)signIdMapForSessionId:(NSString *)arg1 locationRequired:(_Bool)arg2 withCompletion:(void (^)(NSString *, NSError *))arg3 latitude:(NSNumber *)arg4 longitude:(NSNumber *)arg5;
- (void)didSelectPlanItem:(CTCellularPlanItem *)arg1 completion:(void (^)(_Bool, NSError *))arg2;
- (void)willDisplayPlanItems;
- (void)planItemsWithCompletion:(void (^)(NSArray *, NSError *))arg1;
- (void)shouldShowPlanList:(void (^)(_Bool))arg1;
- (void)isAddButtonEnabled:(void (^)(_Bool))arg1;
- (void)triggerAddNewDataPlan:(void (^)(NSError *))arg1;
- (void)isRoamingPlanSupportAvailable:(void (^)(_Bool))arg1;
- (void)isMultipleDataPlanSupportAvailable:(void (^)(_Bool))arg1;
- (void)isNewDataPlanCapable:(void (^)(_Bool))arg1;
@end

