//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <AVKit/AVNowPlayingInfoPanelItemList.h>

@protocol AVNowPlayingInfoPanelFilmStripDelegate;

__attribute__((visibility("hidden")))
@interface AVNowPlayingInfoPanelFilmStrip : AVNowPlayingInfoPanelItemList
{
    id <AVNowPlayingInfoPanelFilmStripDelegate> _filmStripDelegate;
}

@property(nonatomic) __weak id <AVNowPlayingInfoPanelFilmStripDelegate> filmStripDelegate; // @synthesize filmStripDelegate=_filmStripDelegate;
- (void).cxx_destruct;
- (void)collectionView:(id)arg1 didSelectItemAtIndexPath:(id)arg2;
- (long long)collectionView:(id)arg1 numberOfItemsInSection:(long long)arg2;
- (struct CGSize)preferredContentSize;
- (unsigned long long)numberOfItems;
- (void)reloadFilmStripFramesRange:(struct _NSRange)arg1;
- (void)reloadFilmStripFrames;
- (struct CGSize)displayImageSizeForIndexPath:(id)arg1;
- (struct CGSize)displaySizeOfImages;
- (struct CGSize)_displaySizeOfImage:(id)arg1;
- (id)titleForIndexPath:(id)arg1;
- (id)imageForIndexPath:(id)arg1;
- (unsigned long long)numberOfFrames;
- (id)initWithIdentifier:(id)arg1;

@end

