//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSURL.h>

@interface NSURL (_AVPrivateExtendedFileAttributeSupport)
- (_Bool)_setValue:(id)arg1 ofExtendedAttribute:(id)arg2 error:(id *)arg3;
- (id)_extendedAttribute:(id)arg1 error:(id *)arg2;
@end

