//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <CoreRoutine/RTSource.h>

#import <CoreRoutine/NSCopying-Protocol.h>
#import <CoreRoutine/NSSecureCoding-Protocol.h>

@interface RTSourceAudio : RTSource <NSSecureCoding, NSCopying>
{
    long long _audioSource;
}

+ (_Bool)supportsSecureCoding;
+ (id)stringFromAudioSource:(long long)arg1;
@property(readonly, nonatomic) long long audioSource; // @synthesize audioSource=_audioSource;
- (id)description;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)initWithAudioSource:(long long)arg1;

@end

