//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <IBCocoaTouchToolFoundation/UINavigationControllerTemplate.h>

@class NSArray;

@interface UIImagePickerControllerTemplate : UINavigationControllerTemplate
{
    long long sourceType;
    NSArray *mediaTypes;
    _Bool allowsImageEditing;
}

@property _Bool allowsImageEditing; // @synthesize allowsImageEditing;
@property long long sourceType; // @synthesize sourceType;
@property(copy) NSArray *mediaTypes; // @synthesize mediaTypes;
- (void).cxx_destruct;
- (void)encodeWithCoder:(id)arg1;

@end

