//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface FMKeychainManager : NSObject
{
}

+ (id)sharedInstance;
- (id)_query:(id)arg1;
- (int)_delete:(id)arg1;
- (int)_updateWithQuery:(id)arg1 attributes:(id)arg2;
- (int)_add:(id)arg1;
- (id)allRecords;
- (id)allAccountsForService:(id)arg1;
- (id)allServices;
- (id)passwordForAccount:(id)arg1 service:(id)arg2;
- (_Bool)setPassword:(id)arg1 forAccount:(id)arg2 service:(id)arg3;
- (id)dataForAccount:(id)arg1 service:(id)arg2;
- (_Bool)setData:(id)arg1 forAccount:(id)arg2 service:(id)arg3;
- (_Bool)deleteDataForAccount:(id)arg1 service:(id)arg2;

@end

